"""The tables, as data. RFC-001 §04 on one side, `snowflake/sql/` on the other.

`chip_chat.snowflake.account` does this for roles, warehouses and schemas and
says why: `snowflake/sql/` is the only thing that creates anything, and this
module creates nothing. What it adds is a third party to an argument that
otherwise has two -- RFC-001 §04 fixes the schema, `sql/06_catalogue.sql`
through `sql/08_marts.sql` spell it as DDL, and `tests/test_schema_layout.py`
holds the second to the first through this.

Four things are declared here that the DDL cannot check about itself:

**Which columns RFC-001 §04 actually prints.** :attr:`Table.rfc` is §04
transcribed, and it is the whole of "match the schema exactly" as a test. A
column that disappears from a ``CREATE TABLE`` fails `make ci` rather than
being noticed by whoever writes the query that needed it.

**Why every other column is there.** :attr:`Table.additions` pairs each column
§04 does not print with the reason it exists, and the test asserts that a
table's columns are exactly ``rfc | additions`` -- so a column added without an
argument is a failure, and the argument is a string somebody had to write. Ten
of them are #42's, every one already generated by ``chip_chat.data_gen`` and
conformed by silver. The rest belong to the three tables §04 does not print at
all, which arrived with #46 and whose :attr:`Table.rfc` is therefore empty:
``rewards`` and ``rewards_terms`` in CATALOGUE, because a procedure cannot
validate a redemption against a catalogue that is not here nor accrue at a rate
nobody published, and ``action_receipts`` in ACCOUNTS, because idempotency
needs somewhere durable to remember that a retry key has been spent. An empty
``rfc`` is the loud case: every single column of such a table has to carry its
own argument.

**Which tables are visitor-scoped.** :attr:`Table.visitor_scoped` is the
demo_id rule, and :data:`EXEMPT` is the two tables it does not apply to, with
the reason beside each. `sql/09_audit.sql` asks the live account the same
question and defaults to deny in the same direction; the two are not redundant,
because this one sees the tables somebody wrote down and that one sees the
tables nobody did.

**Which policy guards each of them.** :attr:`Table.policy` names the row access
policy `sql/10_policies.sql` attaches, and :data:`POLICIES` is the two of them
with what each promises about a session that has bound nobody.
`tests/test_row_access_policies.py` compares the two lists in both directions,
which is issue #43's coverage requirement: a visitor-scoped table added without
a policy fails `make ci`, and so does a policy attached to a table nobody
declared visitor-scoped.

The types are not §04's -- §04 fixes no types. They are the producing layer's:
silver's ``DECIMAL(10,2)`` for money and ``DECIMAL(8,2)`` for calories in
CATALOGUE and ACCOUNTS, gold's ``DECIMAL(12,2)``, ``DECIMAL(5,4)`` and
``DECIMAL(12,6)`` in MARTS. A publish (#39) that has to cast is a publish that
had to decide, and nobody wrote that decision down.
"""

from collections.abc import Iterator
from dataclasses import dataclass, field
from typing import Final

from chip_chat.snowflake.account import SchemaName

__all__ = [
    "AUDIT_VIEWS",
    "DEMO_ID",
    "EDITABLE_COLUMNS",
    "EXEMPT",
    "ISOLATION_POLICY",
    "MAINTENANCE_VARIABLE",
    "MART_INPUTS",
    "POLICIES",
    "ROSTER_POLICY",
    "SESSION_VARIABLE",
    "TABLES",
    "Addition",
    "Column",
    "Policy",
    "Table",
    "columns_of",
    "policy",
    "table",
    "tables_in",
    "visitor_scoped",
]

DEMO_ID: Final = "demo_id"
"""The column the whole of RFC-001 §05 hangs on.

Every visitor-scoped table carries it, #43's row access policies compare
against it, and a session that has not set the variable behind it sees nothing.
A visitor-scoped table without this column is not a table with a missing
convenience -- it is a table no policy can be written for.
"""

SESSION_VARIABLE: Final = "DEMO_ID"
"""The Snowflake session variable that holds the bound visitor.

The app sets it on checkout and clears it on return (#44); every policy in
`sql/10_policies.sql` reads it with ``GETVARIABLE``. It is spelled once here so
that the pool, the verification and the policies cannot drift apart -- a pool
setting ``DEMO`` while the policies read ``DEMO_ID`` is a demo where every table
returns nothing, which looks like an empty database rather than like a bug.
"""

MAINTENANCE_VARIABLE: Final = "ALL_VISITORS"
"""The second variable :data:`ISOLATION_POLICY` needs before it will cross
visitors, and it is only honoured for :data:`~chip_chat.snowflake.account.ADMIN_ROLE`.

Default deny survives the escape because of this: an owner session that has
bound nobody reads zero rows exactly as a lane role does, and a cross-visitor
read has to be asked for by name. `chip_chat.snowflake.load` asks for it --
counting the rows it has just landed is precisely a question about every
visitor -- and nothing that serves a conversation ever does.
"""

EDITABLE_COLUMNS: Final = ("display_name", "home_store_override", "stated_preferences")
"""The three fields a visitor may change, and they are all on ``demo_visitors``.

The placement is the mechanism rather than a rule to remember: the nightly jobs
compute marts from :data:`MART_INPUTS` only, so no editable field is an input to
a mart and an edit cannot make one stale. `test_schema_layout.py` asserts that
none of these names appears on any other table, which is the property
docs/decisions/persona-editing.md argues and the one a reviewer would otherwise
have to check by reading every job.
"""

EDITABLE_COLUMN_TABLES: Final[dict[str, str]] = {
    "demo_visitors": (
        "where a visitor's edit actually lands, and PRD Q2's answer is that it "
        "lands here and nowhere a nightly job reads"
    ),
    "demo_visitor_baseline": (
        "#47's copy of what the generator made, held so that ageing a session "
        "out can put the three columns back. It carries them for the same "
        "reason a backup carries what it backs up, and it is safe for the same "
        "reason demo_visitors is: no mart is computed from it, no publish "
        "reads it, and nothing writes it but a load. The direction that would "
        "matter is the opposite one -- a THIRD table growing a copy of these "
        "columns that some job does read"
    ),
}
"""The tables :data:`EDITABLE_COLUMNS` may appear on, and why each may.

Two, and the list is closed by `test_schema_layout.py` rather than by a name
skipped in an assertion: a copy of ``stated_preferences`` on a table a nightly
job reads would undo PRD Q2's containment quietly, and the check that catches
that has to be about every other table rather than about these.
"""

MART_INPUTS: Final = ("orders", "order_items", "loyalty_ledger")
"""The only account tables the gold marts are computed from. Not
``demo_visitors``, and that absence is what the paragraph above is about."""

AUDIT_VIEWS: Final = ("visitor_scoped_tables", "tables_missing_demo_id")
"""The two views `sql/09_audit.sql` creates, in ``CHIP_CHAT.ACCOUNTS``.

The second must always return zero rows. `chip_chat.snowflake.verify` asks the
live account, as ``CHIP_CHAT_ADMIN`` -- INFORMATION_SCHEMA hides objects a
narrower role may not see, even through a view, so a lesser role gets a shorter
list and a pass it did not earn.
"""

ISOLATION_POLICY: Final = "visitor_isolation"
"""The row access policy nine of the ten visitor-scoped tables carry.

A row belongs to the visitor bound to the session and to nobody else, and an
unbound session reads zero rows rather than all of them. `sql/10_policies.sql`
is the body; :data:`POLICIES` is what a test can hold it to.
"""

ROSTER_POLICY: Final = "entry_roster"
"""The eighth, and the one inversion in the mechanism.

``persona_fixtures`` is the roster the entry flow chooses a visitor's synthetic
customer from, so it is read on a connection that has bound nobody. This policy
opens that case and only that case: bind a visitor and the same table returns
that visitor's fixture and no other.
"""

EXEMPT: Final[dict[tuple[SchemaName, str], str]] = {
    ("ACCOUNTS", "personas"): (
        "seven archetypes shared by five hundred customers. A row is a kind of "
        "person rather than a person, so there is no visitor to scope it to"
    ),
    ("MARTS", "item_affinity"): (
        "which items are ordered together, over the whole population. A fact "
        "about two items and about nobody -- and the only personalization "
        "input a visitor with no history has"
    ),
}
"""The tables the demo_id rule does not apply to, and why.

Two, and the list is closed by a test rather than by convention: anything else
in ACCOUNTS or MARTS is visitor-scoped. `sql/09_audit.sql` carries the same two
exemptions in its own SQL, where the live audit can read them.
"""


@dataclass(frozen=True, slots=True)
class Column:
    """One column, as the DDL declares it.

    Attributes:
        name: The column name, spelled as RFC-001 §04 spells it. Snowflake
            stores unquoted identifiers upper-cased, so every comparison
            against a live account is case-insensitive.
        sql_type: The declared type, exactly as written in the ``CREATE OR
            ALTER TABLE``.
        required: Whether it is ``NOT NULL`` -- the one constraint Snowflake
            actually enforces, and therefore the only place an invariant can
            be put rather than asserted.
    """

    name: str
    sql_type: str
    required: bool = False


@dataclass(frozen=True, slots=True)
class Addition:
    """A column RFC-001 §04 does not print, and the reason it is here anyway.

    Attributes:
        column: The column name.
        why: What a serving layer without it cannot do. Written out because
            "the schema is fixed, match it exactly" is the instruction, and an
            addition with no argument beside it is a drift.
    """

    column: str
    why: str


@dataclass(frozen=True, slots=True)
class Policy:
    """One row access policy, and what it promises about an unbound session.

    The body itself is not here. It lives in `sql/10_policies.sql` and nowhere
    else -- a policy expression copied into Python is a second thing to keep
    true, and the copy is the one a reviewer would read. What is here is the
    part a test can hold the SQL to.

    Attributes:
        name: The policy, as `sql/10_policies.sql` creates it.
        open_when_unbound: Whether a session that has set no
            :data:`SESSION_VARIABLE` sees rows. False is default deny and is the
            whole of RFC-001 §05; True is an inversion that has to be argued
            for, and `test_row_access_policies.py` allows exactly one.
        why: For an inverted policy, what breaks without the inversion and why
            it is narrower than leaving the table unprotected. For a
            default-deny policy, what it is for.
    """

    name: str
    open_when_unbound: bool
    why: str


POLICIES: Final[tuple[Policy, ...]] = (
    Policy(
        ISOLATION_POLICY,
        open_when_unbound=False,
        why=(
            "the isolation mechanism. A visitor's connection is physically "
            "incapable of returning another visitor's rows however broad the "
            "query Cortex Analyst generates, and an unset session variable "
            "returns nothing rather than everything"
        ),
    ),
    Policy(
        ROSTER_POLICY,
        open_when_unbound=True,
        why=(
            "persona_fixtures is the roster the entry flow picks a visitor's "
            "synthetic customer FROM, and switching personas mints a new "
            "demo_id on a clean connection -- both reads happen before any "
            "visitor is bound, so a default-deny policy would return an empty "
            "roster and break entry rather than protect it. Inverting the "
            "unbound case only is strictly narrower than the alternative of "
            "leaving the table with no policy: the state that can read the "
            "whole roster is the lane that has no visitor to leak it to, "
            "rather than every bound conversation for the life of the demo"
        ),
    ),
)
"""Both policies. Two, and a third would need an argument written beside it.

The set is closed by `test_row_access_policies.py`: every visitor-scoped table
names one of these, exactly one of them may be open when unbound, and the open
one may guard exactly one table.
"""


@dataclass(frozen=True, slots=True)
class Table:
    """One table, and what it promises.

    Attributes:
        name: The table name.
        schema: Which of the three schemas it lives in.
        columns: Every column, in the order the DDL declares them.
        key: The columns of the declared ``PRIMARY KEY``. Metadata, not an
            enforced constraint -- Snowflake enforces only ``NOT NULL`` -- but
            #45's semantic view reads it to know what a row is.
        rfc: RFC-001 §04's columns for this table, transcribed. Empty for a
            table §04 does not print at all.
        additions: The columns beyond ``rfc``, each with its argument.
        visitor_scoped: Whether every row belongs to one visitor. True means
            the table carries :data:`DEMO_ID` and carries a row access policy.
        policy: The row access policy `sql/10_policies.sql` attaches to it, or
            the empty string for a table the demo_id rule does not apply to.
            Visitor-scoped and unguarded is not a state
            `test_row_access_policies.py` allows, in either direction.
        source: The ``<name>.jsonl`` `chip_chat.snowflake.load` fills it from,
            when that is not the table's own name. Empty for every table but
            one: ``demo_visitor_baseline`` is a second projection of the
            generator's ``demo_visitors`` export, and a baseline copied from
            anything other than the file the live table was loaded from would
            be a baseline nobody could check.
    """

    name: str
    schema: SchemaName
    columns: tuple[Column, ...]
    key: tuple[str, ...]
    rfc: tuple[str, ...]
    visitor_scoped: bool
    additions: tuple[Addition, ...] = field(default_factory=tuple)
    policy: str = ""
    source: str = ""

    def column_names(self) -> tuple[str, ...]:
        """Return the column names, in declaration order."""
        return tuple(column.name for column in self.columns)

    def source_name(self) -> str:
        """Return the export this table is loaded from: :attr:`source` or its name."""
        return self.source or self.name

    def qualified(self) -> str:
        """Return ``CHIP_CHAT.ACCOUNTS.orders`` and the like."""
        return f"CHIP_CHAT.{self.schema}.{self.name}"


# ---------------------------------------------------------------------------
# CATALOGUE -- real, harvested, versioned
# ---------------------------------------------------------------------------

_MENU_ITEMS = Table(
    name="menu_items",
    schema="CATALOGUE",
    columns=(
        Column("item_id", "VARCHAR", required=True),
        Column("name", "VARCHAR", required=True),
        Column("category", "VARCHAR"),
        Column("description", "VARCHAR"),
        Column("calories", "NUMBER(8,2)"),
        Column("allergens", "ARRAY"),
        Column("allergen_disclosure", "VARCHAR", required=True),
        Column("source_url", "VARCHAR", required=True),
        Column("harvested_at", "TIMESTAMP_NTZ", required=True),
    ),
    key=("item_id",),
    rfc=(
        "item_id",
        "name",
        "category",
        "description",
        "calories",
        "allergens",
        "source_url",
        "harvested_at",
    ),
    additions=(
        Addition(
            "allergen_disclosure",
            "an empty allergens array has two meanings -- Chipotle publishes "
            "allergen data for this item and marks none of it, or Chipotle "
            "publishes nothing about this item at all -- and only one of them "
            "is a statement anybody made. Without the column the array reads "
            "as a promise. docs/decisions/allergen-absence.md",
        ),
    ),
    visitor_scoped=False,
)

_ITEM_PRICES = Table(
    name="item_prices",
    schema="CATALOGUE",
    columns=(
        Column("restaurant_id", "NUMBER(10,0)", required=True),
        Column("item_id", "VARCHAR", required=True),
        Column("unit_price", "NUMBER(10,2)", required=True),
        Column("unit_delivery_price", "NUMBER(10,2)", required=True),
        Column("is_available", "BOOLEAN", required=True),
        Column("source_url", "VARCHAR", required=True),
        Column("harvested_at", "TIMESTAMP_NTZ", required=True),
    ),
    key=("restaurant_id", "item_id"),
    rfc=(
        "restaurant_id",
        "item_id",
        "unit_price",
        "unit_delivery_price",
        "is_available",
        "source_url",
        "harvested_at",
    ),
    visitor_scoped=False,
)

_MODIFIERS = Table(
    name="modifiers",
    schema="CATALOGUE",
    columns=(
        Column("modifier_id", "VARCHAR", required=True),
        Column("item_id", "VARCHAR", required=True),
        Column("modifier_item_id", "VARCHAR", required=True),
        Column("name", "VARCHAR", required=True),
        Column("delta_calories", "NUMBER(8,2)"),
    ),
    key=("modifier_id",),
    rfc=("modifier_id", "item_id", "name", "delta_calories"),
    additions=(
        Addition(
            "modifier_item_id",
            "the thing added is itself a priced item, so this is the join into "
            "item_prices that answers what adding guacamole costs here. "
            "modifier_id already contains it, spelled <item_id>:<this>; "
            "without the column, pricing a modifier means splitting a string "
            "inside a generated query",
        ),
    ),
    visitor_scoped=False,
)

_STORES = Table(
    name="stores",
    schema="CATALOGUE",
    columns=(
        Column("store_id", "NUMBER(10,0)", required=True),
        Column("name", "VARCHAR"),
        Column("city", "VARCHAR"),
        Column("region", "VARCHAR"),
        Column("hours", "ARRAY"),
    ),
    key=("store_id",),
    rfc=("store_id", "name", "city", "region", "hours"),
    visitor_scoped=False,
)

_REWARDS = Table(
    name="rewards",
    schema="CATALOGUE",
    columns=(
        Column("reward_id", "VARCHAR", required=True),
        Column("position", "NUMBER(10,0)", required=True),
        Column("name", "VARCHAR", required=True),
        Column("point_cost", "NUMBER(10,0)", required=True),
        Column("image_path", "VARCHAR"),
        Column("source_url", "VARCHAR", required=True),
        Column("harvested_at", "TIMESTAMP_NTZ", required=True),
    ),
    key=("reward_id",),
    rfc=(),
    additions=(
        Addition(
            "reward_id",
            "the one invented column in CATALOGUE, and it says so. The "
            "published tiles carry a name, a cost and a picture and no "
            "identifier at all; redeem_points has to name a reward somehow. A "
            "slug keyed to the published name and position, so re-harvesting "
            "the same line-up mints the same ids. docs/action-surface.md "
            "\u00a710 row 2",
        ),
        Addition(
            "position",
            "where the reward falls in the published line-up. The only "
            "ordering the page gives, and half of what reward_id is keyed to "
            "-- a reward that moves is one whose id has to be re-derived "
            "rather than assumed",
        ),
        Addition(
            "name",
            "the reward as published, verbatim, mixed casing and all. A "
            "receipt quotes the reward the visitor was offered, and "
            "normalising it here would be an edit to a published string",
        ),
        Addition(
            "point_cost",
            "what it costs in points. Re-read at redemption rather than taken "
            "from the card: the terms let Chipotle change it at any time, so a "
            "cost read a minute ago is a quote and not a guarantee",
        ),
        Addition(
            "image_path",
            "the picture published beside it, verbatim, and deliberately not "
            "resolved into an item_id. Half the tiles are marketing art and "
            "the slug behind SIDE TORTILLA points at a $0.00 modifier rather "
            "than the $0.50 side of the same name. cc-b5a decides whether the "
            "join can be made at all",
        ),
        Addition(
            "source_url",
            "the page the reward was read from. Half of a citation, and the "
            "page a visitor can be shown when they ask what a reward costs",
        ),
        Addition(
            "harvested_at",
            "when that page was fetched. A point cost quoted without a date is "
            "a number RFC-001 \u00a708 does not accept on a receipt",
        ),
    ),
    visitor_scoped=False,
)

_REWARDS_TERMS = Table(
    name="rewards_terms",
    schema="CATALOGUE",
    columns=(
        Column("rule", "VARCHAR", required=True),
        Column("value", "NUMBER(10,0)", required=True),
        Column("source_url", "VARCHAR", required=True),
        Column("harvested_at", "TIMESTAMP_NTZ", required=True),
    ),
    key=("rule",),
    rfc=(),
    additions=(
        Addition(
            "rule",
            "which published rule the row states, spelled the way data-gen's "
            "rewards.py spells it, so the generated ledger and the live "
            "procedures are arithmetic over one vocabulary rather than two",
        ),
        Addition(
            "value",
            "the number the terms state. place_order multiplies an order total "
            "by points_per_dollar and rejects the order outright when this row "
            "is missing -- a balance accrued at a guessed rate cannot be "
            "un-guessed later, and data-gen took the same rate out of its own "
            "config file for the same reason",
        ),
        Addition(
            "source_url",
            "the document the rule was read from. Every number here is one "
            "somebody published, and a published number without its document "
            "is one nobody can check",
        ),
        Addition(
            "harvested_at",
            "when that document was fetched. A rate can change, and a receipt "
            "says which harvest of the terms it earned under",
        ),
    ),
    visitor_scoped=False,
)

# ---------------------------------------------------------------------------
# ACCOUNTS -- synthetic, visitor-scoped
# ---------------------------------------------------------------------------

_PERSONAS = Table(
    name="personas",
    schema="ACCOUNTS",
    columns=(
        Column("persona_id", "VARCHAR", required=True),
        Column("label", "VARCHAR", required=True),
        Column("home_store", "NUMBER(10,0)"),
        Column("seed_points", "NUMBER(10,0)"),
        Column("narrative", "VARCHAR"),
    ),
    key=("persona_id",),
    rfc=("persona_id", "label", "home_store", "seed_points", "narrative"),
    visitor_scoped=False,
)

_DEMO_VISITORS = Table(
    name="demo_visitors",
    schema="ACCOUNTS",
    columns=(
        Column("demo_id", "VARCHAR", required=True),
        Column("display_name", "VARCHAR"),
        Column("persona_id", "VARCHAR", required=True),
        Column("thread_id", "VARCHAR"),
        Column("home_store_override", "NUMBER(10,0)"),
        Column("stated_preferences", "VARCHAR"),
        Column("created_at", "TIMESTAMP_NTZ", required=True),
        Column("last_seen", "TIMESTAMP_NTZ"),
    ),
    key=("demo_id",),
    rfc=(
        "demo_id",
        "display_name",
        "persona_id",
        "thread_id",
        "home_store_override",
        "stated_preferences",
        "created_at",
        "last_seen",
    ),
    visitor_scoped=True,
    policy=ISOLATION_POLICY,
)

_DEMO_VISITOR_BASELINE = Table(
    name="demo_visitor_baseline",
    schema="ACCOUNTS",
    columns=(
        Column("demo_id", "VARCHAR", required=True),
        Column("display_name", "VARCHAR"),
        Column("home_store_override", "NUMBER(10,0)"),
        Column("stated_preferences", "VARCHAR"),
        Column("created_at", "TIMESTAMP_NTZ", required=True),
        Column("last_seen", "TIMESTAMP_NTZ"),
    ),
    key=("demo_id",),
    rfc=(),
    additions=(
        Addition(
            "demo_id",
            "which customer this is the generated state of. Also what #43's "
            "row access policy compares against: a baseline is as much a fact "
            "about one visitor as the row it restores",
        ),
        Addition(
            "display_name",
            "the invented name data-gen minted for this customer. A visitor "
            "may change it, and #47's reset has nowhere else to read the "
            "original from -- persona_fixtures deliberately carries no name, "
            "because a narrative with a name baked into it goes stale the "
            "moment somebody edits one",
        ),
        Addition(
            "home_store_override",
            "and stated_preferences below: the other two of "
            "EDITABLE_COLUMNS. Both are generated non-null for some customers, "
            "so restoring them to NULL would not be a restore",
        ),
        Addition(
            "stated_preferences",
            "see home_store_override. Held verbatim rather than re-derived: "
            "the generator picked one of a fixed list at random and nothing "
            "downstream can work out which",
        ),
        Addition(
            "created_at",
            "when this customer's history begins. Never edited by anything, "
            "and here so that a reviewer comparing this table against "
            "demo_visitors is comparing whole rows rather than a projection",
        ),
        Addition(
            "last_seen",
            "the generated value, which is their last generated order. The "
            "reset puts it back, which is what makes an aged-out visitor "
            "indistinguishable from one who was never assigned",
        ),
    ),
    visitor_scoped=True,
    policy=ISOLATION_POLICY,
    source="demo_visitors",
)

_PERSONA_FIXTURES = Table(
    name="persona_fixtures",
    schema="ACCOUNTS",
    columns=(
        Column("demo_id", "VARCHAR", required=True),
        Column("persona_id", "VARCHAR", required=True),
        Column("label", "VARCHAR", required=True),
        Column("rank", "NUMBER(10,0)", required=True),
        Column("home_store", "NUMBER(10,0)"),
        Column("home_store_name", "VARCHAR"),
        Column("store_share", "FLOAT"),
        Column("distinct_stores", "NUMBER(10,0)"),
        Column("entrees_per_order", "FLOAT"),
        Column("order_count", "NUMBER(10,0)"),
        Column("lifetime_spend", "NUMBER(10,2)"),
        Column("first_order_at", "TIMESTAMP_NTZ"),
        Column("last_order_at", "TIMESTAMP_NTZ"),
        Column("days_since_order", "NUMBER(10,0)"),
        Column("points_balance", "NUMBER(10,0)"),
        Column("usual_item_id", "VARCHAR"),
        Column("usual_modifiers", "ARRAY"),
        Column("usual_share", "FLOAT"),
        Column("distinct_baskets", "NUMBER(10,0)"),
        Column("narrative", "VARCHAR"),
    ),
    key=("persona_id", "rank"),
    rfc=(
        "demo_id",
        "persona_id",
        "label",
        "rank",
        "home_store",
        "points_balance",
        "usual_item_id",
        "usual_modifiers",
        "usual_share",
        "narrative",
    ),
    additions=(
        Addition(
            "home_store_name",
            "the narrative names a real restaurant or it names none. Read off "
            "the catalogue rather than composed",
        ),
        Addition(
            "store_share",
            "the fixture's own evidence. RFC-001 §04 says of this table that "
            "some columns are elided, and these are they: the narrative is "
            "written FROM these numbers, so a row carrying the sentence and "
            "none of its measurements cannot be doubted usefully. "
            "docs/decisions/persona-fixtures.md",
        ),
        Addition(
            "distinct_stores",
            "how many restaurants they have used at all. The Explorer's "
            "narrative claims variety and this is the count behind the claim",
        ),
        Addition(
            "entrees_per_order",
            "above two is somebody ordering for other people, which is the "
            "only way the group orderer is visible in the row",
        ),
        Addition(
            "order_count",
            "the denominator under store_share and usual_share. A share "
            "without it cannot be told from a share of three orders",
        ),
        Addition(
            "lifetime_spend",
            "what those orders totalled. The narrative does not always quote "
            "it, and a reviewer checking the fixture against customer_360 "
            "does",
        ),
        Addition(
            "first_order_at",
            "when their history starts. With last_order_at it is the span the "
            "measurements above were taken over",
        ),
        Addition(
            "last_order_at",
            "their most recent order, and what days_since_order counts from",
        ),
        Addition(
            "days_since_order",
            "measured to the end of the generated window, not to now, so the "
            "Lapsed Customer does not lapse further every day",
        ),
        Addition(
            "distinct_baskets",
            "how many different baskets they have ordered. The Explorer's "
            "defining number, and the one a low usual_share is only "
            "interesting beside",
        ),
    ),
    visitor_scoped=True,
    policy=ROSTER_POLICY,
)

_ORDERS = Table(
    name="orders",
    schema="ACCOUNTS",
    columns=(
        Column("order_id", "VARCHAR", required=True),
        Column("demo_id", "VARCHAR", required=True),
        Column("store_id", "NUMBER(10,0)", required=True),
        Column("placed_at", "TIMESTAMP_NTZ", required=True),
        Column("status", "VARCHAR", required=True),
        Column("total", "NUMBER(10,2)", required=True),
        Column("channel", "VARCHAR", required=True),
        Column("priced_restaurant_id", "NUMBER(10,0)"),
    ),
    key=("order_id",),
    rfc=("order_id", "demo_id", "store_id", "placed_at", "status", "total"),
    additions=(
        Addition(
            "channel",
            "the catalogue publishes two prices per item, counter and "
            "delivery, so a total is unexplainable until the row says which "
            "list priced it",
        ),
        Addition(
            "priced_restaurant_id",
            "and thirty restaurants publish different numbers, so the row also "
            "says whose prices. Equal to store_id where the harvest priced "
            "that restaurant",
        ),
    ),
    visitor_scoped=True,
    policy=ISOLATION_POLICY,
)

_ORDER_ITEMS = Table(
    name="order_items",
    schema="ACCOUNTS",
    columns=(
        Column("order_id", "VARCHAR", required=True),
        Column("line_number", "NUMBER(10,0)", required=True),
        Column("demo_id", "VARCHAR", required=True),
        Column("item_id", "VARCHAR", required=True),
        Column("qty", "NUMBER(10,0)", required=True),
        Column("modifiers", "ARRAY"),
        Column("unit_price", "NUMBER(10,2)"),
        Column("line_total", "NUMBER(10,2)"),
    ),
    key=("order_id", "line_number"),
    rfc=("order_id", "item_id", "qty", "modifiers"),
    additions=(
        Addition(
            "demo_id",
            "RFC-001 §04 omits it from this table's printed columns and "
            "requires it in the sentence above them, and #43 names order_items "
            "among the tables that get a row access policy. A policy filters "
            "one table against a session variable and cannot follow a join, so "
            "reaching the visitor through orders is not available to it",
        ),
        Addition(
            "line_number",
            "§04 keys a line by (order_id, item_id), which cannot hold two "
            "burritos built differently -- and a group order that cannot is "
            "not a group order",
        ),
        Addition(
            "unit_price",
            "without it orders.total is a number nobody can audit; with it a "
            "reviewer re-derives the total from item_prices and finds it",
        ),
        Addition(
            "line_total",
            "qty times unit_price plus every modifier's own published price. "
            "The same argument as unit_price, and the column that makes the "
            "arithmetic between the two checkable rather than assumed",
        ),
    ),
    visitor_scoped=True,
    policy=ISOLATION_POLICY,
)

_LOYALTY_LEDGER = Table(
    name="loyalty_ledger",
    schema="ACCOUNTS",
    columns=(
        Column("entry_id", "VARCHAR", required=True),
        Column("demo_id", "VARCHAR", required=True),
        Column("delta", "NUMBER(10,0)", required=True),
        Column("reason", "VARCHAR", required=True),
        Column("order_id", "VARCHAR"),
        Column("reward_name", "VARCHAR"),
        Column("created_at", "TIMESTAMP_NTZ", required=True),
    ),
    key=("entry_id",),
    rfc=("entry_id", "demo_id", "delta", "reason", "created_at"),
    additions=(
        Addition(
            "order_id",
            "reconciling the ledger against the orders that earned it should "
            "be a join rather than a regeneration. Null for an opening balance "
            "and for an expiry, the two movements that are about no order",
        ),
        Addition(
            "reward_name",
            "issue #27 requires every redemption to trace to a published "
            "reward, and a cost is not an identity: two rewards can be priced "
            "the same",
        ),
    ),
    visitor_scoped=True,
    policy=ISOLATION_POLICY,
)

_ACTION_RECEIPTS = Table(
    name="action_receipts",
    schema="ACCOUNTS",
    columns=(
        Column("demo_id", "VARCHAR", required=True),
        Column("retry_key", "VARCHAR", required=True),
        Column("action", "VARCHAR", required=True),
        Column("subject_id", "VARCHAR"),
        Column("receipt", "VARIANT", required=True),
        Column("created_at", "TIMESTAMP_NTZ", required=True),
    ),
    key=("demo_id", "retry_key"),
    rfc=(),
    additions=(
        Addition(
            "demo_id",
            "whose attempt it was, and the first half of the key. A retry key "
            "is a fact about one visitor's attempt; a global key space would "
            "let one visitor's retry collide with another's, which is a "
            "cross-visitor effect in the table added to make writes safe",
        ),
        Addition(
            "retry_key",
            "the idempotency key the ops API minted for one confirmed action, "
            "opaque to this table. Issue #46's second acceptance criterion -- "
            "double-submitting one key produces one order -- is not a property "
            "a procedure can hold without somewhere durable to remember that a "
            "key has been spent",
        ),
        Addition(
            "action",
            "which procedure spent it. A key is spent against one action, so a "
            "replay reaching a different procedure is a rejection rather than "
            "a receipt for something the visitor never asked for",
        ),
        Addition(
            "subject_id",
            "what the call wrote, as an identifier: an order_id, a reward_id, "
            "or null for update_preferences, which changes columns on a row "
            "that already existed. A reviewer walks from a spent key to the "
            "row it made without opening the receipt",
        ),
        Addition(
            "receipt",
            "the receipt the first call returned, stored whole and replayed "
            "verbatim. Whole rather than re-derived: a receipt recomputed on "
            "replay would quote today's prices for an order placed yesterday, "
            "and a receipt is a record of what the visitor was told",
        ),
        Addition(
            "created_at",
            "when the key was spent, UTC. What the nightly reset (#47) ages a "
            "row out on, and the timestamp that makes a replay identifiable "
            "as one",
        ),
    ),
    visitor_scoped=True,
    policy=ISOLATION_POLICY,
)

# ---------------------------------------------------------------------------
# MARTS -- derived, published nightly
# ---------------------------------------------------------------------------

_DERIVED_AT = Addition(
    "derived_at",
    "RFC-001 §10 requires a stale mart to be served WITH its timestamp and "
    "never silently as fresh, and a mart with nowhere to put one cannot be. "
    "The gold layer produces it for the same reason",
)

_CUSTOMER_360 = Table(
    name="customer_360",
    schema="MARTS",
    columns=(
        Column("demo_id", "VARCHAR", required=True),
        Column("order_count", "NUMBER(38,0)"),
        Column("lifetime_spend", "NUMBER(12,2)"),
        Column("last_order_at", "TIMESTAMP_NTZ"),
        Column("favourite_store", "NUMBER(10,0)"),
        Column("cadence_days", "NUMBER(8,2)"),
        Column("lapsed_flag", "BOOLEAN"),
        Column("derived_at", "TIMESTAMP_NTZ"),
    ),
    key=("demo_id",),
    rfc=(
        "demo_id",
        "order_count",
        "lifetime_spend",
        "last_order_at",
        "favourite_store",
        "cadence_days",
        "lapsed_flag",
    ),
    additions=(_DERIVED_AT,),
    visitor_scoped=True,
    policy=ISOLATION_POLICY,
)

_USUAL_ORDER = Table(
    name="usual_order",
    schema="MARTS",
    columns=(
        Column("demo_id", "VARCHAR", required=True),
        Column("item_id", "VARCHAR"),
        Column("modifiers", "ARRAY"),
        Column("confidence", "NUMBER(5,4)"),
        Column("derived_at", "TIMESTAMP_NTZ"),
    ),
    key=("demo_id",),
    rfc=("demo_id", "item_id", "modifiers", "confidence", "derived_at"),
    visitor_scoped=True,
    policy=ISOLATION_POLICY,
)

_ITEM_AFFINITY = Table(
    name="item_affinity",
    schema="MARTS",
    columns=(
        Column("item_id", "VARCHAR", required=True),
        Column("related_item_id", "VARCHAR", required=True),
        Column("lift", "NUMBER(12,6)"),
        Column("derived_at", "TIMESTAMP_NTZ"),
    ),
    key=("item_id", "related_item_id"),
    rfc=("item_id", "related_item_id", "lift"),
    additions=(_DERIVED_AT,),
    visitor_scoped=False,
)

_SPEND_SUMMARY = Table(
    name="spend_summary",
    schema="MARTS",
    columns=(
        Column("demo_id", "VARCHAR", required=True),
        Column("period", "VARCHAR", required=True),
        Column("total", "NUMBER(12,2)"),
        Column("order_count", "NUMBER(38,0)"),
        Column("derived_at", "TIMESTAMP_NTZ"),
    ),
    key=("demo_id", "period"),
    rfc=("demo_id", "period", "total", "order_count"),
    additions=(_DERIVED_AT,),
    visitor_scoped=True,
    policy=ISOLATION_POLICY,
)

TABLES: Final[tuple[Table, ...]] = (
    _MENU_ITEMS,
    _ITEM_PRICES,
    _MODIFIERS,
    _STORES,
    _REWARDS,
    _REWARDS_TERMS,
    _PERSONAS,
    _DEMO_VISITORS,
    _DEMO_VISITOR_BASELINE,
    _PERSONA_FIXTURES,
    _ORDERS,
    _ORDER_ITEMS,
    _LOYALTY_LEDGER,
    _ACTION_RECEIPTS,
    _CUSTOMER_360,
    _USUAL_ORDER,
    _ITEM_AFFINITY,
    _SPEND_SUMMARY,
)
"""Every table, in the order `snowflake/sql/` creates them.

The order is load-bearing in the DDL rather than decorative: a ``FOREIGN KEY``
needs the table it references to exist, so ``demo_visitors`` is created before
``persona_fixtures`` points at it.
"""


def table(name: str) -> Table:
    """Return one table by name.

    Args:
        name: An unqualified table name, in any case.

    Returns:
        The declaration.

    Raises:
        KeyError: If no table is called that.
    """
    for candidate in TABLES:
        if candidate.name.upper() == name.upper():
            return candidate
    raise KeyError(f"no table {name!r} in CHIP_CHAT")


def policy(name: str) -> Policy:
    """Return one row access policy by name.

    Args:
        name: A policy name, in any case.

    Returns:
        The declaration.

    Raises:
        KeyError: If no policy is called that.
    """
    for candidate in POLICIES:
        if candidate.name.upper() == name.upper():
            return candidate
    raise KeyError(f"no row access policy {name!r} in CHIP_CHAT")


def tables_in(schema_name: SchemaName) -> Iterator[Table]:
    """Yield the tables of ``schema_name``, in :data:`TABLES` order."""
    for candidate in TABLES:
        if candidate.schema == schema_name:
            yield candidate


def visitor_scoped() -> Iterator[Table]:
    """Yield every table the :data:`DEMO_ID` rule applies to."""
    for candidate in TABLES:
        if candidate.visitor_scoped:
            yield candidate


def columns_of(name: str) -> tuple[str, ...]:
    """Return one table's column names, in declaration order."""
    return table(name).column_names()
