"""Which customers are worth showing a visitor, and the sentence that says why.

Issue #26. The population generated by issue #25 contains five hundred
customers and seven archetypes; this picks out the handful of them a visitor is
actually assigned on arrival, and writes each one's story from their own
history.

The ticket states the rule this module is arranged around, and it is absolute:

    If a fixture cannot demonstrate its own metric, it is not finished.

So a customer becomes a fixture only by clearing the bounds their archetype
sets on their own defining behaviour. The Regular needs a usual so dominant
that reordering in one turn is obviously possible; the Lapsed Customer needs
months of silence *and* unredeemed points, or PRD requirement P3 has nothing to
surface; the Explorer needs orders varied enough that no usual stands out,
which is the point rather than a defect — it is what exercises the honest
"I am not sure what your usual is" path. The bounds are in ``population.toml``
beside the archetype and every one of them is checked here. Nothing else can
make a customer a fixture.

**Selection never invents and never pads.** An archetype with fewer qualifying
customers than :attr:`~chip_chat.data_gen.config.GeneratorConfig.fixtures_per_persona`
contributes the ones it has. A sixty-customer population honestly yields fewer
fixtures than a five-hundred-customer one, and saying so is better than
promoting a customer who fails their own test to make a count come out right —
that is precisely how a demo ends up assigning a visitor "the Regular" who has
no usual. Whether the *shipped* population is thin in this way is a question
about the shipped config, and ``test_fixtures.py`` asks it.

**Selection reads no editable column.** The facts below come from ``orders``,
``order_items`` and ``loyalty_ledger``, plus ``demo_visitors.persona_id`` —
which is the one column of that table a visitor cannot edit. The three they can
edit (``display_name``, ``home_store_override``, ``stated_preferences``) are
never read, so a visitor renaming themselves cannot change who the fixtures
are or what their narratives say. That is the same containment RFC-001
section 04 requires of the gold marts, and ``test_fixtures.py`` asserts it by
mutating those three columns and re-selecting.

**This is not the ``usual_order`` mart.** :attr:`CustomerFacts.usual_share` is
a blunt count — the share of a customer's orders that are their commonest
basket — and the mart of RFC-001 section 04 computes a ``confidence`` its own
way in Databricks. The two are deliberately not named the same thing. What
makes them agree about a fixture is not a shared definition but the selection:
customers are taken from the *extremes*, a Regular above ninety per cent and an
Explorer below fifteen, so any sane definition of confidence puts them on the
same sides of the line.
"""

from collections.abc import Mapping, Sequence
from dataclasses import dataclass, fields
from datetime import datetime
from decimal import Decimal

from chip_chat.catalog import MenuCatalog, Store
from chip_chat.data_gen.catalogue import OrderableMenu
from chip_chat.data_gen.config import GeneratorConfig, PersonaSpec
from chip_chat.data_gen.errors import ConfigError
from chip_chat.data_gen.records import (
    Channel,
    DemoVisitor,
    LoyaltyEntry,
    Order,
    OrderItem,
    PersonaFixture,
)

MONTH_NAMES = (
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
)
"""Month names for the narrative, spelled here rather than by ``strftime``.

``%B`` is locale-dependent, and a population whose narratives are in German on
a German laptop is not the byte-identical output issue #25 promises.
"""

Basket = tuple[tuple[str, tuple[str, ...], int], ...]
"""One order flattened into comparable lines: item, modifiers, quantity.

Two orders are "the same order" when their baskets are equal, which means the
same items built the same way in the same quantities. A Regular who switches
from white rice to brown has not repeated their usual, and should not be
counted as having done so.
"""


@dataclass(frozen=True, slots=True)
class CustomerFacts:
    """What one customer's history says about them.

    Every field is a name in :data:`~chip_chat.data_gen.config.MEASURES` and
    may therefore be used as a bound or a ranking key in the config. That
    correspondence is asserted by a test rather than maintained by discipline.

    Facts are measured against the generated window's fixed end, never against
    the wall clock. A lapsed customer who lapses further every day is not a
    reproducible fixture.

    Attributes:
        demo_id: Whose history.
        persona_id: Which archetype they were minted as.
        order_count: How many orders they placed.
        lifetime_spend: What those orders totalled, in dollars.
        days_since_order: Days from their last order to the window's end.
        days_since_first_order: Days from their first order to the window's
            end. Small means new: this is how the Newcomer is recognised.
        usual_share: The share of their orders that are their commonest
            basket, from zero to one.
        distinct_baskets: How many different baskets they have ordered.
        distinct_stores: How many stores they have ordered from.
        store_share: The share of their orders placed at their commonest
            store.
        entrees_per_order: Mean entrees per order. Above two is somebody
            ordering for other people.
        points_balance: What their loyalty ledger sums to.
        favourite_store: The store they order from most, breaking ties by
            store id. ``customer_360.favourite_store``'s definition.
        first_order_at: Their first order.
        last_order_at: Their most recent.
        usual_item_id: The entree in their commonest basket, or ``None`` if it
            carries none.
        usual_modifiers: How that entree is built.
    """

    demo_id: str
    persona_id: str
    order_count: int
    lifetime_spend: Decimal
    days_since_order: int
    days_since_first_order: int
    usual_share: float
    distinct_baskets: int
    distinct_stores: int
    store_share: float
    entrees_per_order: float
    points_balance: int
    favourite_store: int
    first_order_at: datetime
    last_order_at: datetime
    usual_item_id: str | None
    usual_modifiers: tuple[str, ...]

    def measure(self, name: str) -> float:
        """Return one measured fact by name, as a number bounds can compare.

        Args:
            name: A name from :data:`~chip_chat.data_gen.config.MEASURES`.

        Returns:
            The value.

        Raises:
            AttributeError: If ``name`` is not a measure. The config reader
                rejects those before generation, so reaching this is a bug
                rather than a bad config.
        """
        return float(getattr(self, name))

    def satisfies(self, spec: PersonaSpec) -> bool:
        """Return whether this customer clears every bound its archetype sets.

        Args:
            spec: The archetype, whose :attr:`~...config.PersonaSpec.fixture`
                carries the bounds.

        Returns:
            ``True`` only if every bound holds. Every one, not most: a
            Lapsed Customer with the points but not the silence demonstrates
            nothing the Regular does not.
        """
        criteria = spec.fixture
        return all(
            self.measure(name) >= floor for name, floor in criteria.at_least
        ) and all(self.measure(name) <= ceiling for name, ceiling in criteria.at_most)


def measure_customers(
    visitors: Sequence[DemoVisitor],
    orders: Sequence[Order],
    order_items: Sequence[OrderItem],
    ledger: Sequence[LoyaltyEntry],
    entree_ids: frozenset[str],
    window_ends_at: datetime,
) -> tuple[CustomerFacts, ...]:
    """Measure every customer who has placed at least one order.

    A customer with no orders is skipped rather than given zeroes. There is
    nothing to say about them and no narrative to write, and admitting them
    with an empty history would make ``usual_share`` of zero — the Explorer's
    ranking key — rank them first.

    Args:
        visitors: The customers. Only ``demo_id`` and ``persona_id`` are read.
        orders: Every order in the population.
        order_items: Every line of them.
        ledger: Every loyalty movement.
        entree_ids: Which catalogue items count as entrees, from
            :class:`~chip_chat.data_gen.catalogue.OrderableMenu`.
        window_ends_at: The fixed end of the generated history. Recency is
            measured against this and never against now.

    Returns:
        One record per customer with orders, in ``demo_id`` order.
    """
    lines: dict[str, list[tuple[str, tuple[str, ...], int]]] = {}
    for item in order_items:
        lines.setdefault(item.order_id, []).append(
            (item.item_id, item.modifiers, item.qty)
        )

    mine: dict[str, list[Order]] = {}
    for order in orders:
        mine.setdefault(order.demo_id, []).append(order)

    balances: dict[str, int] = {}
    for entry in ledger:
        balances[entry.demo_id] = balances.get(entry.demo_id, 0) + entry.delta

    archetypes = {visitor.demo_id: visitor.persona_id for visitor in visitors}
    return tuple(
        _facts(
            demo_id,
            archetypes[demo_id],
            sorted(mine[demo_id], key=lambda order: order.placed_at),
            lines,
            balances.get(demo_id, 0),
            entree_ids,
            window_ends_at,
        )
        for demo_id in sorted(archetypes)
        if mine.get(demo_id)
    )


def _facts(
    demo_id: str,
    persona_id: str,
    mine: Sequence[Order],
    lines: Mapping[str, Sequence[tuple[str, tuple[str, ...], int]]],
    balance: int,
    entree_ids: frozenset[str],
    window_ends_at: datetime,
) -> CustomerFacts:
    """Measure one customer, given their orders oldest first."""
    baskets = [tuple(sorted(lines.get(order.order_id, ()))) for order in mine]
    usual, repeats = _commonest(baskets)
    stores = [order.store_id for order in mine]
    favourite, at_favourite = _commonest(stores)
    entrees = sum(
        quantity
        for basket in baskets
        for item_id, _, quantity in basket
        if item_id in entree_ids
    )
    item_id, modifiers = _entree_of(usual, entree_ids)
    return CustomerFacts(
        demo_id=demo_id,
        persona_id=persona_id,
        order_count=len(mine),
        lifetime_spend=sum((order.total for order in mine), start=Decimal("0")),
        days_since_order=(window_ends_at - mine[-1].placed_at).days,
        days_since_first_order=(window_ends_at - mine[0].placed_at).days,
        usual_share=repeats / len(baskets),
        distinct_baskets=len(set(baskets)),
        distinct_stores=len(set(stores)),
        store_share=at_favourite / len(stores),
        entrees_per_order=entrees / len(mine),
        points_balance=balance,
        favourite_store=favourite,
        first_order_at=mine[0].placed_at,
        last_order_at=mine[-1].placed_at,
        usual_item_id=item_id,
        usual_modifiers=modifiers,
    )


def _commonest[T](values: Sequence[T]) -> tuple[T, int]:
    """Return the commonest value and how often it appears.

    Ties break on the value itself rather than on the order it was seen in.
    ``Counter.most_common`` breaks them on insertion order, which for a
    customer with two equally frequent baskets would make their usual depend
    on which order happened to be numbered first — reproducible, but for the
    wrong reason, and liable to flip when an unrelated parameter is retuned.
    """
    counts: dict[T, int] = {}
    for value in values:
        counts[value] = counts.get(value, 0) + 1
    best = max(counts, key=lambda value: (counts[value], _tiebreak(value)))
    return best, counts[best]


def _tiebreak(value: object) -> str:
    """Return a total order over baskets and store ids alike."""
    return repr(value)


def _entree_of(
    basket: Basket, entree_ids: frozenset[str]
) -> tuple[str | None, tuple[str, ...]]:
    """Return the entree in a basket and how it is built, if it has one.

    The first entree by item id, so a family ordering three of them has a
    stable answer. A basket of only chips and a drink has none, and says so
    rather than naming the chips: "your usual is a bag of chips" is a worse
    answer than admitting there is no usual entree.
    """
    for item_id, modifiers, _ in sorted(basket):
        if item_id in entree_ids:
            return item_id, modifiers
    return None, ()


def select_fixtures(
    facts: Sequence[CustomerFacts],
    config: GeneratorConfig,
    catalog: MenuCatalog,
    stores: Sequence[Store],
) -> tuple[PersonaFixture, ...]:
    """Choose each archetype's exemplars and write their narratives.

    Args:
        facts: Every measured customer.
        config: The tuned parameters, whose archetypes carry the criteria.
        catalog: The catalogue, for the published names the narrative uses.
            Only names are read from it; every identifier already came from it
            by way of the generator.
        stores: The stores the population orders from.

    Returns:
        The fixtures, archetype by archetype in config order and best first
        within each. Fewer than
        :attr:`~chip_chat.data_gen.config.GeneratorConfig.fixtures_per_persona`
        for an archetype whose customers do not supply that many, and none at
        all for one whose customers supply none.

    Raises:
        ConfigError: If an archetype's narrative template names a field the
            facts do not carry. Refused rather than rendered, because the
            alternative is showing a visitor a literal ``{placeholder}``.
    """
    names = {item.item_id: item.name for item in catalog.menu_items}
    modifiers = {row.modifier_id: row.name for row in catalog.modifiers}
    store_names = {store.store_id: store.name for store in stores}

    fixtures: list[PersonaFixture] = []
    for spec in config.personas:
        qualifying = [
            row
            for row in facts
            if row.persona_id == spec.persona_id
            if row.satisfies(spec)
        ]
        direction = 1.0 if spec.fixture.ascending else -1.0
        chosen = sorted(
            qualifying,
            key=lambda row: (direction * row.measure(spec.fixture.measure), row.demo_id),
        )[: config.fixtures_per_persona]
        fixtures.extend(
            _fixture(row, spec, rank, store_names, names, modifiers)
            for rank, row in enumerate(chosen, start=1)
        )
    return tuple(fixtures)


def _fixture(
    row: CustomerFacts,
    spec: PersonaSpec,
    rank: int,
    store_names: Mapping[int, str | None],
    item_names: Mapping[str, str],
    modifier_names: Mapping[str, str],
) -> PersonaFixture:
    """Build one fixture row, narrative included."""
    store_name = store_names.get(row.favourite_store)
    usual_name = item_names.get(row.usual_item_id) if row.usual_item_id else None
    return PersonaFixture(
        demo_id=row.demo_id,
        persona_id=spec.persona_id,
        label=spec.label,
        rank=rank,
        home_store=row.favourite_store,
        home_store_name=store_name,
        store_share=row.store_share,
        distinct_stores=row.distinct_stores,
        entrees_per_order=row.entrees_per_order,
        order_count=row.order_count,
        lifetime_spend=row.lifetime_spend,
        first_order_at=row.first_order_at,
        last_order_at=row.last_order_at,
        days_since_order=row.days_since_order,
        points_balance=row.points_balance,
        usual_item_id=row.usual_item_id,
        usual_modifiers=row.usual_modifiers,
        usual_share=row.usual_share,
        distinct_baskets=row.distinct_baskets,
        narrative=_narrative(
            spec,
            row,
            store_name=store_name,
            usual_item_name=usual_name,
            usual_order=_describe(row.usual_modifiers, usual_name, modifier_names),
        ),
    )


def _narrative(
    spec: PersonaSpec,
    row: CustomerFacts,
    *,
    store_name: str | None,
    usual_item_name: str | None,
    usual_order: str,
) -> str:
    """Fill an archetype's template from one customer's measured facts.

    Every number the sentence contains is a column of the fixture row and
    every food it names is a published name, which is what makes issue #26's
    third acceptance criterion — "good enough to paste directly into an
    opening message" — a claim about real data rather than about prose.
    """
    supplied = {name: getattr(row, name) for name in _FACT_NAMES} | {
        "store": store_name if store_name else f"store {row.favourite_store}",
        "usual_item_name": usual_item_name or "no one thing",
        "usual_order": usual_order,
        "last_order_month": _month(row.last_order_at),
        "first_order_month": _month(row.first_order_at),
    }
    try:
        return spec.fixture.narrative.format(**supplied)
    except (KeyError, IndexError, ValueError) as error:
        raise ConfigError(
            f"personas[{spec.persona_id}].fixture.narrative does not render "
            f"against a customer's facts: {error}. A narrative is shown to a "
            f"visitor, so a template that cannot be filled is refused rather "
            f"than rendered with the hole in it. Available fields: "
            f"{sorted(supplied)}"
        ) from error


_FACT_NAMES = tuple(field.name for field in fields(CustomerFacts))
"""Every fact a narrative template may name, taken from the record itself."""


def _describe(
    modifiers: Sequence[str], item_name: str | None, modifier_names: Mapping[str, str]
) -> str:
    """Return a published item and how it is built, as English.

    Names come out of the catalogue and nowhere else. This is the sentence
    fragment that makes the ticket's example — "a well-documented weakness for
    double barbacoa" — writable, and it is also the one place a narrative
    could name a food, so it names only foods Chipotle publishes.
    """
    if item_name is None:
        return "nothing in particular"
    named = [modifier_names[key] for key in modifiers if key in modifier_names]
    if not named:
        return item_name
    if len(named) == 1:
        return f"{item_name} with {named[0].lower()}"
    listed = ", ".join(name.lower() for name in named[:-1])
    return f"{item_name} with {listed} and {named[-1].lower()}"


def _month(when: datetime) -> str:
    """Return ``"April 2026"`` for an instant, locale-independently."""
    return f"{MONTH_NAMES[when.month - 1]} {when.year}"


def entree_ids(menu: OrderableMenu) -> frozenset[str]:
    """Return every item the catalogue publishes as an entree, on any channel.

    Both channels, because an entree that is counter-only is still an entree
    and a customer who ordered one still ordered a meal.

    Args:
        menu: The orderable view of the catalogue.

    Returns:
        The item identifiers.
    """
    return frozenset(
        buildable.item.item_id
        for channel in Channel
        for buildable in menu.entrees(channel)
    )
