"""When the account lane declines, which RFC-001 §10 makes a requirement.

`chip_chat.snowflake.analyst` is the one sentence in that table -- *a Cortex
Analyst timeout or low confidence returns "I can't answer that reliably" and
never a fallback hand-written query* -- written as a function, and this is where
the sentence gets held to. Free and offline: :func:`~chip_chat.snowflake.analyst.decide`
makes no call, so every branch of it is reachable from a dictionary.

The responses below are the real shapes, trimmed. They were taken from
``/api/v2/cortex/analyst/message`` against this account on 2026-08-27: the
verified path returns a CTE per logical table, the generated path returns
``SELECT * FROM SEMANTIC_VIEW(...)``, and the path with no answer returns
suggestions and no ``sql`` part at all.

The tests that matter most are the ones about SQL that came back and was
refused anyway. A refusal on a timeout is easy and nobody gets it wrong. A
refusal of a statement that arrived, parsed and would have run is the one
RFC-001 §10 is actually about, because that is the moment a fallback query
looks reasonable.
"""

import pytest

from chip_chat.snowflake import account, analyst, semantic

VERIFIED_SQL = (
    "WITH __points AS (SELECT delta AS point_change FROM "
    "CHIP_CHAT.ACCOUNTS.LOYALTY_LEDGER) SELECT SUM(l.point_change) AS "
    "points_balance FROM __points AS l -- Generated by Cortex Analyst"
)
GENERATED_SQL = (
    "SELECT * FROM SEMANTIC_VIEW(CHIP_CHAT.ACCOUNTS.ACCOUNT_LANE METRICS "
    "last_order_at WHERE store_city = 'NH Town 1')"
)


def response(*content: dict) -> dict:
    """Wrap content parts the way the REST API wraps them."""
    return {"message": {"role": "analyst", "content": list(content)}}


def sql_part(statement: str, *, verified: str = "") -> dict:
    """One ``sql`` content part, with or without a verified query behind it."""
    confidence = {"verified_query_used": {"name": verified} if verified else None}
    return {"type": "sql", "statement": statement, "confidence": confidence}


# ---------------------------------------------------------------------------
# The thresholds
# ---------------------------------------------------------------------------


def test_an_unset_environment_is_the_argued_default() -> None:
    """Doing nothing gets the defaults, not an unthresholded lane."""
    thresholds = analyst.Thresholds.from_env({})
    assert thresholds.timeout_seconds == analyst.DEFAULT_TIMEOUT_SECONDS
    assert thresholds.min_confidence == analyst.CONFIDENCE[analyst.Path.GENERATED]


def test_the_default_deadline_fits_inside_the_warehouses() -> None:
    """The Analyst call and the SQL it produces both have to fit in one turn.

    The serving warehouse kills a statement at sixty seconds; this bounds the
    hop before it. A deadline at or above the warehouse's would mean the lane
    was still waiting when the query it is waiting for had already been killed.
    """
    serving = next(
        warehouse
        for warehouse in account.WAREHOUSES
        if warehouse.name == account.SERVING_WAREHOUSE
    )
    assert serving.statement_timeout_seconds > analyst.DEFAULT_TIMEOUT_SECONDS


@pytest.mark.parametrize(
    "variable",
    [analyst.TIMEOUT_VARIABLE, analyst.MIN_CONFIDENCE_VARIABLE],
)
def test_a_threshold_that_does_not_parse_fails_at_startup(variable: str) -> None:
    """A misspelled number that quietly kept the default is worse than a crash.

    The same argument as `vision.matcher.SlotRules.from_env`: a lane tuned
    against a threshold nobody set is a measurement of the wrong thing.
    """
    with pytest.raises(ValueError, match=variable):
        analyst.Thresholds.from_env({variable: "quite high"})


def test_a_deadline_of_zero_is_refused() -> None:
    """It would decline every question before asking it, which is not a policy."""
    with pytest.raises(ValueError, match="decline every question"):
        analyst.Thresholds.from_env({analyst.TIMEOUT_VARIABLE: "0"})


def test_a_floor_outside_the_ladder_is_refused() -> None:
    """1.5 is not "stricter than verified"; it is a lane that never answers."""
    with pytest.raises(ValueError, match=r"\[0, 1\]"):
        analyst.Thresholds.from_env({analyst.MIN_CONFIDENCE_VARIABLE: "1.5"})


def test_both_thresholds_are_read_from_the_environment() -> None:
    """#45's fourth criterion: configured, not compiled in."""
    thresholds = analyst.Thresholds.from_env(
        {analyst.TIMEOUT_VARIABLE: "4", analyst.MIN_CONFIDENCE_VARIABLE: "1"}
    )
    assert thresholds.timeout_seconds == 4.0
    assert thresholds.min_confidence == 1.0
    assert thresholds.admits(analyst.Path.VERIFIED)
    assert not thresholds.admits(analyst.Path.GENERATED)


# ---------------------------------------------------------------------------
# Answering
# ---------------------------------------------------------------------------


def test_a_verified_answer_is_returned_with_the_query_that_matched() -> None:
    """The top rung, and the one a person wrote and a test covers."""
    decision = analyst.decide(
        response(sql_part(VERIFIED_SQL, verified="POINTS_BALANCE")),
        elapsed_seconds=2.3,
    )
    assert decision.answered
    assert decision.path is analyst.Path.VERIFIED
    assert decision.confidence == 1.0
    assert decision.verified_query == "POINTS_BALANCE"
    assert decision.sql == VERIFIED_SQL


def test_generated_sql_is_answered_by_default() -> None:
    """Refusing everything unverified would refuse most of PRD A2.

    Aggregates and time ranges are the reason Cortex Analyst is in the design
    at all, and nobody can enumerate them in advance.
    """
    decision = analyst.decide(response(sql_part(GENERATED_SQL)), elapsed_seconds=4.1)
    assert decision.answered
    assert decision.path is analyst.Path.GENERATED
    assert decision.sql == GENERATED_SQL


def test_a_verified_only_floor_refuses_generated_sql() -> None:
    """A supported position, and what a demo in front of an audience wants."""
    decision = analyst.decide(
        response(sql_part(GENERATED_SQL)),
        elapsed_seconds=4.1,
        thresholds=analyst.Thresholds(min_confidence=1.0),
    )
    assert not decision.answered
    assert not decision.sql
    assert "floor" in decision.reason


def test_the_interpretation_survives_onto_the_decision() -> None:
    """Analyst restates the question, and a trace is better for having it."""
    decision = analyst.decide(
        response(
            {"type": "text", "text": "This is our interpretation of your question:"},
            sql_part(GENERATED_SQL),
        ),
        elapsed_seconds=1.0,
    )
    assert decision.interpretation.startswith("This is our interpretation")


# ---------------------------------------------------------------------------
# Declining
# ---------------------------------------------------------------------------


def test_a_slow_answer_is_declined_even_though_it_arrived() -> None:
    """A turn that took too long has failed as a conversation whatever it said."""
    decision = analyst.decide(
        response(sql_part(VERIFIED_SQL, verified="POINTS_BALANCE")),
        elapsed_seconds=30.0,
    )
    assert not decision.answered
    assert decision.path is analyst.Path.UNAVAILABLE
    assert not decision.sql
    assert "deadline" in decision.reason


def test_nothing_coming_back_is_declined_rather_than_raised() -> None:
    """A lane may fail; the conversation may not fail with it."""
    decision = analyst.decide(None, elapsed_seconds=0.2)
    assert not decision.answered
    assert decision.path is analyst.Path.UNAVAILABLE


def test_suggestions_without_sql_are_a_refusal_and_keep_the_suggestions() -> None:
    """Analyst offering other questions IS Analyst declining this one.

    The suggestions are worth carrying: they are the model saying what it does
    cover, which is a better thing to put in front of a visitor than silence.
    """
    decision = analyst.decide(
        response(
            {
                "type": "suggestions",
                "suggestions": ["what have i spent this year", "what do i order most"],
            }
        ),
        elapsed_seconds=3.0,
    )
    assert not decision.answered
    assert decision.path is analyst.Path.SUGGESTED
    assert decision.suggestions == (
        "what have i spent this year",
        "what do i order most",
    )


def test_a_query_that_names_a_visitor_is_refused_even_when_it_would_run() -> None:
    """The guard that is not about confidence at all.

    No tool signature carries a visitor identifier (RFC-001 §06) and the model
    is told never to filter on one, so a statement that does is either an
    invented literal or a reach at somebody else's rows. Both are refusals.
    """
    decision = analyst.decide(
        response(
            sql_part(
                "SELECT SUM(total) FROM CHIP_CHAT.ACCOUNTS.orders "
                "WHERE demo_id = 'demo-0001'"
            )
        ),
        elapsed_seconds=2.0,
    )
    assert not decision.answered
    assert not decision.sql
    assert "demo_id" in decision.reason


def test_a_query_that_leaves_the_model_is_refused() -> None:
    """The bound is the point of #45, and it is checked rather than trusted."""
    decision = analyst.decide(
        response(
            sql_part(
                "SELECT SUM(m.calories) FROM CHIP_CHAT.ACCOUNTS.order_items li "
                "JOIN CHIP_CHAT.CATALOGUE.item_prices m ON m.item_id = li.item_id"
            )
        ),
        elapsed_seconds=2.0,
    )
    assert not decision.answered
    assert "item_prices" in decision.reason


def test_a_query_against_another_semantic_view_is_refused() -> None:
    """There is one account lane, and a second view would be a second boundary."""
    decision = analyst.decide(
        response(sql_part("SELECT * FROM SEMANTIC_VIEW(CHIP_CHAT.MARTS.SOMETHING)")),
        elapsed_seconds=2.0,
    )
    assert not decision.answered
    assert "SOMETHING" in decision.reason


@pytest.mark.parametrize(
    "statement",
    [
        "DELETE FROM CHIP_CHAT.ACCOUNTS.orders",
        "UPDATE CHIP_CHAT.ACCOUNTS.loyalty_ledger SET delta = 1000",
        "SELECT 1 FROM CHIP_CHAT.ACCOUNTS.orders; DROP TABLE CHIP_CHAT.ACCOUNTS.orders",
    ],
)
def test_anything_that_is_not_a_single_read_is_refused(statement: str) -> None:
    """CHIP_CHAT_READ would be refused these anyway. Declining first is cheaper.

    And it is the difference between a span that says what the lane declined
    and a Snowflake error nobody attributes to the account lane.
    """
    decision = analyst.decide(response(sql_part(statement)), elapsed_seconds=1.0)
    assert not decision.answered


def test_every_table_the_view_models_is_allowed_through() -> None:
    """The guard bounds; it must not also block what the model does carry."""
    for table in semantic.LOGICAL_TABLES:
        qualified = f"CHIP_CHAT.{table.schema}.{table.table}"
        assert not analyst.reads_only_the_view(f"SELECT 1 FROM {qualified}"), (
            f"{qualified} is in the semantic view and the guard refuses it"
        )


def test_a_refusal_never_carries_sql() -> None:
    """RFC-001 §10's actual prohibition, as a property of every refusal path.

    "Never a fallback hand-written query" is easy to keep by not writing one.
    It is lost the other way: a decision that declines and still hands its
    caller a statement is a fallback query with extra steps.
    """
    declines = (
        analyst.decide(None, elapsed_seconds=0.1),
        analyst.decide(response(sql_part(VERIFIED_SQL)), elapsed_seconds=99.0),
        analyst.decide(response({"type": "suggestions"}), elapsed_seconds=1.0),
        analyst.decide(
            response(sql_part("SELECT 1 FROM CHIP_CHAT.MARTS.customer_360")),
            elapsed_seconds=1.0,
        ),
        analyst.decide(
            response(sql_part(GENERATED_SQL)),
            elapsed_seconds=1.0,
            thresholds=analyst.Thresholds(min_confidence=1.0),
        ),
    )
    for decision in declines:
        assert not decision.answered
        assert decision.sql == ""
        assert decision.reason


def test_the_refusal_is_the_sentence_the_rfc_wrote() -> None:
    """One sentence, whatever declined and why. The reason is for the span."""
    assert analyst.REFUSAL == "I can't answer that reliably"
