"""That the catalogue can be written, read back, and started from.

Two of issue #24's acceptance criteria live here. The tables have to be
"produced and loadable", which is checked by writing a catalogue, reading it
with :func:`~chip_chat.catalog.load_catalog`, and asserting the result equals
what was written — a claim that a written-only table cannot make. And row
counts and a sample have to be committed as a fixture "so downstream work can
start without a live harvest", which is checked by regenerating the committed
fixture and comparing it byte for byte.

The committed fixture is generated by ``regenerate_fixture.py`` from the
fixture site, so it is a small catalogue rather than a real one. That is the
point: it exists so that issue #25's generator and issue #54's matcher have
something to resolve against on a laptop with no network. A production
catalogue is built by ``python -m chip_chat.catalog`` against a real landing
zone, and no catalogue built from these fixtures should ever be served.
"""

from pathlib import Path

import pytest
from catalog_fixtures import FIXTURES, fixture_catalog

from chip_chat.catalog import MenuCatalog, load_catalog, render_module
from chip_chat.catalog.errors import CatalogLoadError
from chip_chat.harvest.blobs import InMemoryBlobStore, LocalBlobStore

CATALOG_PREFIX = "catalog"
VOCABULARY_FILE = FIXTURES / "vision-vocabulary.py.txt"
REGENERATE = "uv run python catalog/tests/regenerate_fixture.py"


def written(catalog: MenuCatalog) -> dict[str, bytes]:
    """Serialise a catalogue into a mapping of key to bytes."""
    blobs = InMemoryBlobStore()
    catalog.write(blobs, CATALOG_PREFIX)
    return {key: blobs.read(key) or b"" for key in blobs.keys(CATALOG_PREFIX)}


def test_a_written_catalogue_reads_back_equal() -> None:
    """The whole of "loadable", asserted rather than assumed."""
    catalog = fixture_catalog()
    blobs = InMemoryBlobStore()
    catalog.write(blobs, CATALOG_PREFIX)
    loaded = load_catalog(blobs, CATALOG_PREFIX)

    assert loaded == catalog
    assert loaded.version() == catalog.version()
    assert loaded.content_version() == catalog.content_version()


def test_the_decimals_come_back_as_decimals() -> None:
    """A price that round-tripped through a float would be quietly wrong."""
    catalog = fixture_catalog()
    blobs = InMemoryBlobStore()
    catalog.write(blobs, CATALOG_PREFIX)
    loaded = load_catalog(blobs, CATALOG_PREFIX)

    prices = {row.item_id: row.unit_price for row in loaded.item_prices}
    assert str(prices["CMG-2"]) == "13.15"
    assert str(prices["CMG-2"]) == str(
        {row.item_id: row.unit_price for row in catalog.item_prices}["CMG-2"]
    )


def test_an_altered_table_is_refused_rather_than_loaded() -> None:
    """ "The catalogue says so" is the end of the argument, so it has to be true."""
    catalog = fixture_catalog()
    blobs = InMemoryBlobStore()
    catalog.write(blobs, CATALOG_PREFIX)
    key = f"{CATALOG_PREFIX}/menu_items.jsonl"
    body = (blobs.read(key) or b"").replace(b'"13.15"', b'"1.15"')
    blobs.write(key, body.replace(b"Steak Burrito", b"Wagyu Burrito"))

    with pytest.raises(CatalogLoadError, match="altered since it was written"):
        load_catalog(blobs, CATALOG_PREFIX)


def test_a_missing_table_is_refused() -> None:
    """A catalogue that loads short is worse than one that does not load."""
    catalog = fixture_catalog()
    blobs = InMemoryBlobStore()
    catalog.write(blobs, CATALOG_PREFIX)
    blobs.write(f"{CATALOG_PREFIX}/modifiers.jsonl", b"")

    with pytest.raises(CatalogLoadError, match="modifiers holds 0 rows"):
        load_catalog(blobs, CATALOG_PREFIX)


def test_the_committed_fixture_is_what_this_build_produces() -> None:
    """Regenerate and compare, so the sample cannot describe last week's schema."""
    catalog = fixture_catalog()
    produced = written(catalog)
    committed = {
        key: (LocalBlobStore(FIXTURES).read(key) or b"")
        for key in LocalBlobStore(FIXTURES).keys(CATALOG_PREFIX)
    }

    assert set(committed) == set(produced), (
        f"the committed fixture has different tables from this build; run {REGENERATE}"
    )
    for key, body in produced.items():
        assert committed[key] == body, (
            f"{key} has changed since the fixture was committed; run {REGENERATE}"
        )


def test_the_committed_fixture_loads_without_a_harvest() -> None:
    """The criterion in its own words: downstream can start from this alone."""
    loaded = load_catalog(LocalBlobStore(FIXTURES), CATALOG_PREFIX)

    assert loaded.item("CMG-2") is not None
    assert loaded.reference_restaurant_id == 679
    assert {row.item_id for row in loaded.item_prices} <= {
        row.item_id for row in loaded.menu_items
    }


def test_the_committed_vocabulary_is_what_this_build_generates() -> None:
    """The generated enum file, generated again and compared.

    It is committed as ``.py.txt`` rather than as a module, because it is the
    *output* of a build step and not source. Importing it would make it a
    hand-maintained list with extra steps — and a vocabulary generated from
    these fixtures describes a menu of two entrees, which nothing should ever
    serve.
    """
    catalog = fixture_catalog()
    expected = VOCABULARY_FILE.read_text(encoding="utf-8")
    assert expected == render_module(catalog.vocabulary, catalog.content_version()), (
        f"the generated vocabulary has changed; run {REGENERATE}"
    )


def test_the_committed_fixture_records_its_row_counts() -> None:
    """ "Row counts committed as a fixture", in the manifest beside the tables."""
    import json

    manifest = json.loads(
        (Path(FIXTURES) / CATALOG_PREFIX / "manifest.json").read_text(encoding="utf-8")
    )
    counts = {name: entry["rows"] for name, entry in manifest["tables"].items()}
    assert counts["menu_items"] > 0
    assert counts["stores"] >= 30
    assert set(manifest) == {
        "catalog_version",
        "content_version",
        "reference_restaurant_id",
        "restaurant_ids",
        "tables",
    }
