# Unity Catalog: the catalog, the medallion schemas, and who may write to them.
#
# This runs before there are any tables, on purpose. Ownership and grants are
# cheap to set on an empty catalog and tedious to retrofit onto a populated one,
# because every object created in between inherits whatever was true at the time.
#
# `databricks.tf` stops at "Unity Catalog can reach the data" — the storage
# credential and the two external locations. This file is the governance layer
# that sits on top of them, and `databricks_compute.tf` is the compute the jobs
# below run on.
#
# --- THE SCHEMA NAMES, AND THE ONE DELIBERATE DEVIATION ----------------------
#
# Issue #32 asks for schemas `bronze`, `silver` and `gold` "with the two streams
# — harvested web corpus and synthetic accounts — kept visibly separate within
# them". Unity Catalog has exactly three levels: catalog, schema, table. There is
# no fourth level to put the stream on, so "visibly separate within a schema"
# can only be a table-naming convention — and a naming convention is invisible on
# the day this issue ships, because there are no tables yet.
#
# So the stream is a schema-name suffix and the medallion layer is the prefix:
#
#     chip_chat.bronze_harvested   chip_chat.bronze_synthetic
#     chip_chat.silver_harvested   chip_chat.silver_synthetic
#     chip_chat.gold_harvested     chip_chat.gold_synthetic
#
# This costs a longer name and buys three things a convention cannot. The
# boundary is visible in the catalogue browser with nothing in it yet. It is
# grantable — a principal can be given the real catalogue and not the synthetic
# accounts, which is the enforcement RFC-001 §04 wants and which no table prefix
# can express. And it is a *property of the object*, recorded in `properties`
# below, so a query against `information_schema.schemata` can assert the layout
# rather than parse it out of names.
#
# RFC-001 §04: "Keeping the boundary explicit in the schema keeps it explicit in
# conversation." This is that sentence, spelled as six schemas.
#
# Gold is split like the other two rather than being one shared mart schema,
# because both streams really do have a serving layer: the harvested side
# publishes the versioned catalogue and the retrieval chunks, the synthetic side
# publishes the four personalization marts in RFC-001 §04. A single `gold` would
# be the one place in the design where the two populations sit in the same
# namespace, which is exactly the blur this layout exists to prevent.

locals {
  # Unity Catalog identifiers are unquoted SQL identifiers in every query anyone
  # will ever write against them, and `chip-chat` would have to be backticked in
  # all of them. `local.base` is a resource-name convention; this is a SQL one.
  uc_catalog = replace(local.base, "-", "_")

  # Where the catalog's managed tables live. A subdirectory of the lakehouse
  # container rather than its root, so that the per-schema roots below are
  # siblings of it rather than nested inside it — Unity Catalog rejects a
  # managed location that overlaps another one.
  uc_catalog_storage_root = "abfss://${azurerm_storage_container.lakehouse.name}@${azurerm_storage_account.data.name}.dfs.core.windows.net/_catalog"

  uc_schema_storage_prefix = "abfss://${azurerm_storage_container.lakehouse.name}@${azurerm_storage_account.data.name}.dfs.core.windows.net/schemas"

  # The medallion, as data. Terraform builds the six schemas from this and the
  # `chip_chat.databricks.catalog` Python module carries the same list for the
  # pipelines in #33 and #34; `databricks/tests/test_catalog_layout.py` asserts
  # the two agree, so a schema added in one place cannot silently miss the other.
  uc_streams = {
    harvested = {
      adjective = "real"
      summary   = "Harvested from Chipotle's published pages. Real, cited, and never invented — every row traces to a source_url and a harvested_at."
    }
    synthetic = {
      adjective = "synthetic"
      summary   = "Generated by data-gen/ against the real catalogue. Personas, orders and loyalty ledgers that never happened, composed only of items that really exist."
    }
  }

  uc_layers = {
    bronze = "As landed. No cleaning, no deduplication, no schema enforcement beyond what the file already had — this layer exists so that a parser bug is recoverable without re-fetching."
    silver = "Cleaned, deduplicated, conformed to the RFC-001 §04 data model. This is the layer a human reads when they want to know what is actually in the corpus."
    gold   = "Serving-ready and published outward. Nothing downstream reads bronze or silver."
  }

  # Layer-and-stream specifics, kept apart from the generic text above so the
  # comment on each schema says something a reader could not have guessed.
  uc_schema_notes = {
    bronze_harvested = "Raw responses from the fetch-once cache in `raw/`, one row per document, still carrying the bytes' SHA-256 as their identity."
    bronze_synthetic = "Generator output exactly as written to ADLS, seeded and reproducible."
    silver_harvested = "menu_items, item_prices, modifiers and stores. Price is keyed by restaurant, not by item — Chipotle's published prices vary ~20% between stores (docs/decisions/menu-pricing.md)."
    silver_synthetic = "personas, orders, order_items and loyalty_ledger, conformed and keyed by demo_id."
    gold_harvested   = "The versioned catalogue published to Snowflake, and the chunked corpus published to Azure AI Search. Both carry source_url and harvested_at through, because RFC-001 §08 requires them as citations and there is nowhere left to recover them from downstream."
    gold_synthetic   = "customer_360, usual_order, item_affinity and spend_summary, published nightly to Snowflake, plus recommendations and the item_affinity_recommender model that batch-scores it (gh-37). Computed from orders, order_items and loyalty_ledger ONLY — never from demo_visitors, because the three fields a visitor may edit live there and no editable field may be an input to a mart (RFC-001 §04)."
  }

  # The cross product, flattened into the map every resource below iterates.
  uc_schemas = {
    for pair in setproduct(keys(local.uc_layers), keys(local.uc_streams)) :
    "${pair[0]}_${pair[1]}" => {
      layer  = pair[0]
      stream = pair[1]
      comment = join(" ", [
        "${title(pair[0])} layer, ${local.uc_streams[pair[1]].adjective} stream.",
        local.uc_layers[pair[0]],
        local.uc_streams[pair[1]].summary,
        local.uc_schema_notes["${pair[0]}_${pair[1]}"],
        "Managed by infra/terraform (gh-32).",
      ])
    }
  }

  # What the job service principal needs to run a Lakeflow declarative pipeline
  # into a schema. CREATE_MATERIALIZED_VIEW is not implied by CREATE_TABLE and is
  # what #33 and #34 will actually create; granting it here means neither issue
  # has to come back and widen a grant to get started.
  #
  # CREATE_MODEL is #37's, and it is here for the same reason and against the
  # belief `databricks_recommender.tf` used to hold: that MODIFY on the schema
  # is what registering a version needs. It is not. MLflow's
  # `log_model(registered_model_name=...)` calls `create_registered_model`
  # first, idempotently, whether or not Terraform already made the model -- and
  # that call is refused with `User does not have CREATE MODEL on Schema
  # 'chip_chat.gold_synthetic'` after the fit, after both hit-rate evaluations,
  # at the last step of the run.
  #
  # It is granted on all six schemas rather than on the one that holds a model,
  # which is a real if small widening: nothing wants a model in
  # `bronze_harvested`. The same is already true of CREATE_MATERIALIZED_VIEW,
  # and one writer list that every schema shares is worth more here than a
  # marginally narrower grant plus a second list to keep in step with it. The
  # grants that decide anything are the per-model ones below and in
  # `databricks_recommender.tf`.
  uc_writer_privileges = [
    "USE_SCHEMA",
    "SELECT",
    "MODIFY",
    "CREATE_TABLE",
    "CREATE_MATERIALIZED_VIEW",
    "CREATE_MODEL",
    "REFRESH",
  ]

  # Deliberately not `BROWSE`, and deliberately not `ALL_PRIVILEGES`. SELECT is
  # the whole of what a reader does.
  uc_reader_privileges = [
    "USE_SCHEMA",
    "SELECT",
  ]
}

# --- The catalog ------------------------------------------------------------

resource "databricks_catalog" "main" {
  count = var.databricks_unity_catalog_enabled ? 1 : 0

  name         = local.uc_catalog
  storage_root = local.uc_catalog_storage_root
  owner        = local.uc_owner
  comment      = "Chip Chat lakehouse. Two streams that must not blur: the real harvested catalogue (`*_harvested`) and the synthetic account data generated against it (`*_synthetic`). See docs/lakehouse-catalog.md and RFC-001 §04. Managed by infra/terraform (gh-32)."

  properties = {
    project = "chip_chat"
    issue   = "gh-32"
    purpose = "medallion"
  }

  # The catalog is created inside an external location, so the location has to
  # exist and the credential behind it has to have been validated first.
  depends_on = [databricks_external_location.lakehouse]

  # Teardown is one command. A catalog that refuses to drop because a schema
  # still exists inside it is exactly the straggler that breaks that promise --
  # and everything in here is derived data that a pipeline run rebuilds.
  force_destroy = true
}

# --- Ownership ---------------------------------------------------------------
#
# Ownership is stated rather than inherited, because inherited means "whoever
# ran the first apply", which is a fact about a laptop rather than a decision.
#
# ⚠️ A UNITY CATALOG OWNER MUST BE AN *ACCOUNT*-LEVEL PRINCIPAL. The obvious
# choice — the `admins` group, which exists in every workspace and already
# contains everyone who could undo this — does not work, and does not fail in a
# way that says so. Unity Catalog answers:
#
#     cannot create catalog: Could not find principal with name admins
#
# which reads like a typo. It is not: `admins` and `users` are WORKSPACE-LOCAL
# groups, and Unity Catalog resolves principals against the account. Making an
# account-level group needs a provider configured at `accounts.azuredatabricks.net`
# and an account admin to run it — the same wall `system.access` and
# on-behalf-of tokens are behind (see `var.databricks_service_principal_token_enabled`).
# Found on this workspace on 2026-08-26.
#
# So the default is the identity running Terraform, which is what #31 already
# left on the external locations, and `var.databricks_catalog_owner` is the seam:
# set it to an account group the day there is one, and the whole catalog moves
# with one apply. A named individual as owner is a single point of failure the
# day that account is disabled, and this is the smallest honest version of that
# arrangement rather than a good one.
locals {
  uc_owner = coalesce(var.databricks_catalog_owner, data.databricks_current_user.me.user_name)
}

# --- Who may do what --------------------------------------------------------
#
# NO AMBIENT FULL ACCESS, which is the phrase issue #32 uses and which has a
# specific meaning in Unity Catalog: the `account users` group. Databricks grants
# it ALL PRIVILEGES on the legacy `main` catalog of a new metastore, and it is
# the grant people copy without noticing. It is absent here and its absence is
# load-bearing — every principal below is named, and nothing else can read this
# catalog at all.
#
# `databricks_grants` is AUTHORITATIVE for the object it names: it does not add
# to what is there, it replaces it. That is what makes the absence enforceable
# rather than merely initial. Somebody who grants themselves something in the
# UI has it removed by the next apply.

resource "databricks_grants" "catalog" {
  count = var.databricks_unity_catalog_enabled ? 1 : 0

  catalog = databricks_catalog.main[0].name

  # USE_CATALOG only. It is a traversal right, not a read right: it lets a
  # principal reach a schema it has been granted separately, and grants nothing
  # about the contents of any of them.
  grant {
    principal  = databricks_service_principal.jobs.application_id
    privileges = ["USE_CATALOG"]
  }

  grant {
    principal  = databricks_service_principal.readonly.application_id
    privileges = ["USE_CATALOG"]
  }

  # The app tier is NOT here, and that is the design rather than an omission.
  # RFC-001 §05 puts every per-turn read in Snowflake behind a row access policy;
  # the app never queries the lakehouse. Giving it a grant it does not use would
  # widen the trust boundary the whole of §05 exists to keep narrow.
}

resource "databricks_schema" "medallion" {
  for_each = var.databricks_unity_catalog_enabled ? local.uc_schemas : {}

  catalog_name = databricks_catalog.main[0].name
  name         = each.key
  owner        = local.uc_owner
  comment      = each.value.comment

  # A managed root per schema, so the real/synthetic boundary is visible in
  # storage and not only in the catalogue. Without it Unity Catalog lays every
  # schema out under one directory keyed by GUID, which is fine for the engine
  # and useless to a human holding a storage browser open.
  storage_root = "${local.uc_schema_storage_prefix}/${each.key}"

  # The layout, machine-readable. `SELECT * FROM system.information_schema.schemata`
  # (or `DESCRIBE SCHEMA EXTENDED`) can then assert the medallion is intact
  # without anyone parsing a name.
  properties = {
    layer   = each.value.layer
    stream  = each.value.stream
    project = "chip_chat"
    issue   = "gh-32"
  }

  force_destroy = true
}

resource "databricks_grants" "medallion" {
  for_each = var.databricks_unity_catalog_enabled ? local.uc_schemas : {}

  schema = databricks_schema.medallion[each.key].id

  grant {
    principal  = databricks_service_principal.jobs.application_id
    privileges = local.uc_writer_privileges
  }

  grant {
    principal  = databricks_service_principal.readonly.application_id
    privileges = local.uc_reader_privileges
  }
}

# --- The reader -------------------------------------------------------------
#
# Issue #32 asks that permissions be "verified by attempting a write with the
# read-only principal and being refused". That needs a principal that really is
# read-only rather than an admin pretending, so here is one. It is also the
# identity anything that consumes gold without producing it should use — the
# Snowflake publish, a notebook someone is reading tables from, a BI tool.
#
# It gets no compute-creation rights, exactly like the jobs principal: the only
# way it can run anything is through `chip-chat-job-single-node`, the policy in
# databricks_compute.tf that #31 made the sole route to compute.

resource "databricks_service_principal" "readonly" {
  display_name = "${local.base}-readonly"

  allow_cluster_create       = false
  allow_instance_pool_create = false
  workspace_access           = true
}

# Same account-level permission the jobs principal needs, and for the same
# reason: `run_as` on a job is `roles/servicePrincipal.user`, an ACCOUNT
# permission that being a workspace admin does not imply. Without it, creating
# the refusal job below fails with "the user creating or updating the job must
# have 'servicePrincipal.user' role on the service principal".
#
# The rule set is authoritative for the principal it names, so the `manager` role
# Databricks grants the creator automatically is restated rather than dropped.
resource "databricks_access_control_rule_set" "readonly_service_principal" {
  name = "accounts/${var.databricks_account_id}/servicePrincipals/${databricks_service_principal.readonly.application_id}/ruleSets/default"

  grant_rules {
    principals = [data.databricks_current_user.me.acl_principal_id]
    role       = "roles/servicePrincipal.manager"
  }

  grant_rules {
    principals = [data.databricks_current_user.me.acl_principal_id]
    role       = "roles/servicePrincipal.user"
  }
}

# --- The two proofs ---------------------------------------------------------
#
# Issue #32's acceptance criteria are three, and two of them are claims about a
# live system rather than about this file: lineage really resolves end to end,
# and the read-only principal really is refused. Both are jobs, so that they are
# something you run rather than something you remember being told — the same
# reasoning as the ADLS smoke job in databricks_compute.tf.
#
# Neither is scheduled. Nothing in this workspace should be able to start
# spending on its own.
#
# Run them in order; the second reads what the first writes:
#
#     databricks jobs run-now $(terraform output -raw databricks_lineage_job_id)
#     databricks jobs run-now $(terraform output -raw databricks_readonly_job_id)

locals {
  # Every job below wants the same cluster shape and differs only in which
  # identity it runs as -- which is the entire point of the second one.
  uc_probe_raw_uri = "abfss://${azurerm_storage_container.raw.name}@${azurerm_storage_account.data.name}.dfs.core.windows.net"
}

resource "databricks_notebook" "lineage_probe" {
  path     = "/Shared/${local.base}/lineage_probe"
  language = "PYTHON"
  source   = "${path.module}/../../databricks/notebooks/lineage_probe.py"
}

resource "databricks_notebook" "readonly_denied" {
  path     = "/Shared/${local.base}/readonly_denied"
  language = "PYTHON"
  source   = "${path.module}/../../databricks/notebooks/readonly_denied.py"
}

resource "databricks_job" "uc_lineage" {
  count = var.databricks_unity_catalog_enabled ? 1 : 0

  name        = "${local.base}-uc-lineage"
  description = "Writes one raw file through bronze, silver and gold, then asserts Unity Catalog recorded the chain. Manual trigger only."

  timeout_seconds     = var.databricks_uc_probe_timeout_seconds
  max_concurrent_runs = 1

  run_as {
    service_principal_name = databricks_service_principal.jobs.application_id
  }

  job_cluster {
    job_cluster_key = "single-node"

    new_cluster {
      policy_id     = databricks_cluster_policy.job_single_node.id
      spark_version = var.databricks_spark_version
      node_type_id  = var.databricks_node_type
      num_workers   = 0

      # Unity Catalog grants apply to the identity the cluster carries, and
      # single-node compute only supports the single-user security mode. This
      # line is what makes the job's grants -- rather than the workspace admin's
      # -- the ones under test.
      data_security_mode = "SINGLE_USER"
      single_user_name   = databricks_service_principal.jobs.application_id

      spark_conf = {
        "spark.databricks.cluster.profile" = "singleNode"
        "spark.master"                     = "local[*]"
      }

      custom_tags = {
        "ResourceClass" = "SingleNode"
        "project"       = "chip_chat"
        "issue"         = "gh-32"
      }
    }
  }

  task {
    task_key        = "lineage"
    job_cluster_key = "single-node"

    notebook_task {
      notebook_path = databricks_notebook.lineage_probe.path
      base_parameters = {
        catalog = databricks_catalog.main[0].name
        raw_uri = local.uc_probe_raw_uri
        run_id  = "{{job.run_id}}"
        cleanup = "false"
      }
    }
  }

  depends_on = [
    databricks_grants.medallion,
    databricks_grants.catalog,
    databricks_grants.raw_external_location,
    databricks_permissions.job_policy_usage,
    databricks_access_control_rule_set.jobs_service_principal,
  ]
}

resource "databricks_job" "uc_readonly_denied" {
  count = var.databricks_unity_catalog_enabled ? 1 : 0

  name        = "${local.base}-uc-readonly-denied"
  description = "Reads a gold table as the read-only principal, then attempts five writes and requires every one to be refused. Manual trigger only. Run chip-chat-uc-lineage first."

  timeout_seconds     = var.databricks_uc_probe_timeout_seconds
  max_concurrent_runs = 1

  # The whole experiment. Everything else in this resource is the same as the
  # job above; this line is the variable.
  run_as {
    service_principal_name = databricks_service_principal.readonly.application_id
  }

  job_cluster {
    job_cluster_key = "single-node"

    new_cluster {
      policy_id     = databricks_cluster_policy.job_single_node.id
      spark_version = var.databricks_spark_version
      node_type_id  = var.databricks_node_type
      num_workers   = 0

      data_security_mode = "SINGLE_USER"
      single_user_name   = databricks_service_principal.readonly.application_id

      spark_conf = {
        "spark.databricks.cluster.profile" = "singleNode"
        "spark.master"                     = "local[*]"
      }

      custom_tags = {
        "ResourceClass" = "SingleNode"
        "project"       = "chip_chat"
        "issue"         = "gh-32"
      }
    }
  }

  task {
    task_key        = "denied"
    job_cluster_key = "single-node"

    notebook_task {
      notebook_path = databricks_notebook.readonly_denied.path
      base_parameters = {
        catalog = databricks_catalog.main[0].name
        raw_uri = local.uc_probe_raw_uri
        run_id  = "{{job.run_id}}"
      }
    }
  }

  depends_on = [
    databricks_grants.medallion,
    databricks_grants.catalog,
    databricks_grants.raw_external_location,
    databricks_permissions.job_policy_usage,
    databricks_access_control_rule_set.readonly_service_principal,
  ]
}

resource "databricks_permissions" "uc_lineage_job" {
  count = var.databricks_unity_catalog_enabled ? 1 : 0

  job_id = databricks_job.uc_lineage[0].id

  access_control {
    service_principal_name = databricks_service_principal.jobs.application_id
    permission_level       = "CAN_MANAGE_RUN"
  }
}

resource "databricks_permissions" "uc_readonly_denied_job" {
  count = var.databricks_unity_catalog_enabled ? 1 : 0

  job_id = databricks_job.uc_readonly_denied[0].id

  access_control {
    service_principal_name = databricks_service_principal.readonly.application_id
    permission_level       = "CAN_MANAGE_RUN"
  }
}
