# Outputs exist so that nothing downstream has to hardcode an identifier that a
# teardown will change. Every name carrying a random suffix is regenerated by
# the next apply — read it from here, not from a table in a README.

output "resource_group_name" {
  description = "Resource group holding the whole estate. `terraform destroy` empties it."
  value       = azurerm_resource_group.main.name
}

output "location" {
  description = "Region. East US 2, forced by Snowflake Cortex Analyst availability."
  value       = azurerm_resource_group.main.location
}

output "key_vault_name" {
  value = azurerm_key_vault.main.name
}

output "key_vault_id" {
  value = azurerm_key_vault.main.id
}

output "key_vault_uri" {
  description = "Vault endpoint. Every secret the app tier reads lives here; none of them are in Terraform."
  value       = azurerm_key_vault.main.vault_uri
}

output "app_identity_client_id" {
  description = "AZURE_CLIENT_ID for DefaultAzureCredential. Changes if the identity is ever recreated."
  value       = azurerm_user_assigned_identity.app.client_id
}

output "app_identity_principal_id" {
  value = azurerm_user_assigned_identity.app.principal_id
}

output "app_identity_id" {
  value = azurerm_user_assigned_identity.app.id
}

output "data_storage_account" {
  description = "ADLS Gen2 account: raw landing zone and photo uploads."
  value       = azurerm_storage_account.data.name
}

output "data_storage_dfs_endpoint" {
  description = "The /dfs endpoint, which is what Databricks and Lakeflow want."
  value       = azurerm_storage_account.data.primary_dfs_endpoint
}

output "raw_container" {
  value = azurerm_storage_container.raw.name
}

output "uploads_container" {
  description = "Photo uploads. Lifecycle rule deletes blobs here 24-48 hours after creation."
  value       = azurerm_storage_container.uploads.name
}

output "search_endpoint" {
  description = "Null while var.search_enabled is false — see that variable for why it exists."
  value       = one(azurerm_search_service.main[*].name) == null ? null : "https://${one(azurerm_search_service.main[*].name)}.search.windows.net"
}

output "search_service_name" {
  value = one(azurerm_search_service.main[*].name)
}

output "foundry_account_name" {
  value = azurerm_cognitive_account.foundry.name
}

output "foundry_endpoint" {
  value = azurerm_cognitive_account.foundry.endpoint
}

output "foundry_project_name" {
  value = azurerm_cognitive_account_project.main.name
}

output "foundry_project_endpoints" {
  description = "Per-API endpoints for the Foundry project, keyed by API name."
  value       = azurerm_cognitive_account_project.main.endpoints
}

output "model_deployment_names" {
  description = "Deployment names on the Foundry account. These are what an inference call passes as `model`."
  value       = keys(azurerm_cognitive_deployment.models)
}

output "model_deployments" {
  description = <<-EOT
    Every deployment with the model, SKU and capacity behind it. This is the
    answer to "what is actually deployed and what does it cost", and it is a
    plain output rather than a table in a README because a teardown and re-apply
    changes it.
  EOT
  value = {
    for name, d in azurerm_cognitive_deployment.models : name => {
      model    = "${d.model[0].name}:${d.model[0].version}"
      sku      = d.sku[0].name
      capacity = d.sku[0].capacity
    }
  }
}

# The two deployments the application reads by role. They are outputs rather
# than literals in the app so that swapping the model behind a lane for an eval
# experiment is a change to var.model_deployments and an environment variable,
# and nothing else. See CHIP_CHAT_FOUNDRY_* in .env.example.
output "foundry_inference_endpoint" {
  description = "OpenAI-shaped inference endpoint on the Foundry account — what the SDK wants as azure_endpoint."
  value       = azurerm_cognitive_account.foundry.endpoint
}

# The registry the agent image is published to. Null when
# var.container_registry_enabled is false.
output "container_registry_name" {
  description = "Registry name — what `az acr login --name` wants."
  value       = one(azurerm_container_registry.main[*].name)
}

output "container_registry_login_server" {
  description = "Registry host — what an image reference is prefixed with, and what `make agent-image-push ACR_LOGIN_SERVER=...` takes."
  value       = one(azurerm_container_registry.main[*].login_server)
}

output "container_registry_id" {
  description = "Resource id, for the federated credential CI pushes with."
  value       = one(azurerm_container_registry.main[*].id)
}

output "agent_image_repository" {
  description = <<-EOT
    Where the agent image lives, without a tag. An agent version pins a digest
    off this repository rather than a tag — see chip_chat.agent.version.
  EOT
  value = (
    one(azurerm_container_registry.main[*].login_server) == null
    ? null
    : "${one(azurerm_container_registry.main[*].login_server)}/chip-chat-agent"
  )
}

output "content_safety_endpoint" {
  value = azurerm_cognitive_account.content_safety.endpoint
}

output "document_intelligence_endpoint" {
  value = azurerm_cognitive_account.document_intelligence.endpoint
}

output "web_fqdn" {
  description = "Public hostname of the chat app, on the Container Apps default domain with its automatic managed certificate. There is no DNS zone and no certificate resource in this stack by design (issue #4)."
  value       = azurerm_container_app.web.ingress[0].fqdn
}

output "web_url" {
  value = "https://${azurerm_container_app.web.ingress[0].fqdn}"
}



output "container_app_name" {
  description = "What `az containerapp update --image` targets when a new image is pushed."
  value       = azurerm_container_app.web.name
}

output "ops_api_hostname" {
  value = azurerm_function_app_flex_consumption.ops.default_hostname
}

output "application_insights_name" {
  value = azurerm_application_insights.main.name
}

output "log_analytics_workspace_name" {
  value = azurerm_log_analytics_workspace.main.name
}

# The App Insights connection string carries an ingestion key, so it is marked
# sensitive and read deliberately rather than printed with everything else:
#   terraform output -raw application_insights_connection_string
output "application_insights_connection_string" {
  value     = azurerm_application_insights.main.connection_string
  sensitive = true
}

output "budget_name" {
  value = azurerm_consumption_budget_subscription.monthly.name
}

# --- Databricks -------------------------------------------------------------

output "databricks_workspace_name" {
  value = azurerm_databricks_workspace.main.name
}

output "databricks_workspace_url" {
  description = "Workspace endpoint. Also written to the Key Vault secret `databricks-host`, so the app tier reads one place for host and token."
  value       = "https://${azurerm_databricks_workspace.main.workspace_url}"
}

output "databricks_workspace_id" {
  value = azurerm_databricks_workspace.main.workspace_id
}

output "databricks_job_policy_id" {
  description = "The single-node, job-only, ten-minute cluster policy. Any new job's compute should reference this rather than restating the rules."
  value       = databricks_cluster_policy.job_single_node.id
}

output "databricks_pipeline_policy_id" {
  description = "Separate policy for Lakeflow pipeline compute — it has no autotermination_minutes, which pipeline compute rejects. Use this one for #33 and #34."
  value       = databricks_cluster_policy.pipeline_single_node.id
}

output "databricks_interactive_policy_id" {
  value = databricks_cluster_policy.interactive_single_node.id
}

output "databricks_jobs_service_principal_application_id" {
  description = "Application id of the service principal automated jobs run as. It has no credential: `run_as` is resolved inside Databricks, so nothing is issued, stored or rotated."
  value       = databricks_service_principal.jobs.application_id
}

output "databricks_app_service_principal_application_id" {
  description = "The id-chip-chat-app managed identity, registered in Databricks. The app tier presents an Entra token as this principal — there is no PAT in the normal path."
  value       = databricks_service_principal.app.application_id
}

output "databricks_access_connector_principal_id" {
  description = "Managed identity Unity Catalog authenticates to ADLS with. Holds Storage Blob Data Contributor on the data account and nothing else."
  value       = azurerm_databricks_access_connector.unity.identity[0].principal_id
}

output "databricks_external_locations" {
  description = "Unity Catalog external locations, keyed by name. Null while var.databricks_unity_catalog_enabled is false."
  value = var.databricks_unity_catalog_enabled ? {
    (databricks_external_location.raw[0].name)       = databricks_external_location.raw[0].url
    (databricks_external_location.lakehouse[0].name) = databricks_external_location.lakehouse[0].url
  } : null
}

output "databricks_smoke_job_id" {
  description = "The end-to-end ADLS job. Run it with: databricks jobs run-now <id>"
  value       = databricks_job.adls_smoke.id
}
