# Outputs exist so that nothing downstream has to hardcode an identifier that a
# teardown will change. Every name carrying a random suffix is regenerated by
# the next apply — read it from here, not from a table in a README.

output "resource_group_name" {
  description = "Resource group holding the whole estate. `terraform destroy` empties it."
  value       = azurerm_resource_group.main.name
}

output "location" {
  description = "Region. East US 2, forced by Snowflake Cortex Analyst availability."
  value       = azurerm_resource_group.main.location
}

output "key_vault_name" {
  value = azurerm_key_vault.main.name
}

output "key_vault_id" {
  value = azurerm_key_vault.main.id
}

output "key_vault_uri" {
  description = "Vault endpoint. Every secret the app tier reads lives here; none of them are in Terraform."
  value       = azurerm_key_vault.main.vault_uri
}

output "app_identity_client_id" {
  description = "AZURE_CLIENT_ID for DefaultAzureCredential. Changes if the identity is ever recreated."
  value       = azurerm_user_assigned_identity.app.client_id
}

output "app_identity_principal_id" {
  value = azurerm_user_assigned_identity.app.principal_id
}

output "app_identity_id" {
  value = azurerm_user_assigned_identity.app.id
}

output "data_storage_account" {
  description = "ADLS Gen2 account: raw landing zone and photo uploads."
  value       = azurerm_storage_account.data.name
}

output "data_storage_dfs_endpoint" {
  description = "The /dfs endpoint, which is what Databricks and Lakeflow want."
  value       = azurerm_storage_account.data.primary_dfs_endpoint
}

output "raw_container" {
  value = azurerm_storage_container.raw.name
}

output "uploads_container" {
  description = "Photo uploads. Lifecycle rule deletes blobs here 24-48 hours after creation."
  value       = azurerm_storage_container.uploads.name
}

output "search_endpoint" {
  description = "Null while var.search_enabled is false — see that variable for why it exists."
  value       = one(azurerm_search_service.main[*].name) == null ? null : "https://${one(azurerm_search_service.main[*].name)}.search.windows.net"
}

output "search_service_name" {
  value = one(azurerm_search_service.main[*].name)
}

output "foundry_account_name" {
  value = azurerm_cognitive_account.foundry.name
}

output "foundry_endpoint" {
  value = azurerm_cognitive_account.foundry.endpoint
}

output "foundry_project_name" {
  value = azurerm_cognitive_account_project.main.name
}

output "foundry_project_endpoints" {
  description = "Per-API endpoints for the Foundry project, keyed by API name."
  value       = azurerm_cognitive_account_project.main.endpoints
}

output "model_deployment_names" {
  description = "Deployment names on the Foundry account. These are what an inference call passes as `model`."
  value       = keys(azurerm_cognitive_deployment.models)
}

output "model_deployments" {
  description = <<-EOT
    Every deployment with the model, SKU and capacity behind it. This is the
    answer to "what is actually deployed and what does it cost", and it is a
    plain output rather than a table in a README because a teardown and re-apply
    changes it.
  EOT
  value = {
    for name, d in azurerm_cognitive_deployment.models : name => {
      model    = "${d.model[0].name}:${d.model[0].version}"
      sku      = d.sku[0].name
      capacity = d.sku[0].capacity
    }
  }
}

# The two deployments the application reads by role. They are outputs rather
# than literals in the app so that swapping the model behind a lane for an eval
# experiment is a change to var.model_deployments and an environment variable,
# and nothing else. See CHIP_CHAT_FOUNDRY_* in .env.example.
output "foundry_inference_endpoint" {
  description = "OpenAI-shaped inference endpoint on the Foundry account — what the SDK wants as azure_endpoint."
  value       = azurerm_cognitive_account.foundry.endpoint
}

output "content_safety_endpoint" {
  value = azurerm_cognitive_account.content_safety.endpoint
}

output "document_intelligence_endpoint" {
  value = azurerm_cognitive_account.document_intelligence.endpoint
}

output "web_fqdn" {
  description = "Public hostname of the chat app, on the Container Apps default domain with its automatic managed certificate. There is no DNS zone and no certificate resource in this stack by design (issue #4)."
  value       = azurerm_container_app.web.ingress[0].fqdn
}

output "web_url" {
  value = "https://${azurerm_container_app.web.ingress[0].fqdn}"
}

output "container_registry_login_server" {
  description = "Registry the chat app's image is pushed to. `az acr login --name <this>` uses your own Entra token; there is no admin password."
  value       = azurerm_container_registry.main.login_server
}

output "container_registry_name" {
  value = azurerm_container_registry.main.name
}

output "container_app_name" {
  description = "What `az containerapp update --image` targets when a new image is pushed."
  value       = azurerm_container_app.web.name
}

output "ops_api_hostname" {
  value = azurerm_function_app_flex_consumption.ops.default_hostname
}

output "application_insights_name" {
  value = azurerm_application_insights.main.name
}

output "log_analytics_workspace_name" {
  value = azurerm_log_analytics_workspace.main.name
}

# The App Insights connection string carries an ingestion key, so it is marked
# sensitive and read deliberately rather than printed with everything else:
#   terraform output -raw application_insights_connection_string
output "application_insights_connection_string" {
  value     = azurerm_application_insights.main.connection_string
  sensitive = true
}

output "budget_name" {
  value = azurerm_consumption_budget_subscription.monthly.name
}
