"""The medallion layout, as data.

Unity Catalog is created by Terraform — `infra/terraform/databricks_catalog.tf`
is the only thing that makes a catalog or a schema, and this module makes
nothing. What it does is stop the pipelines in #33 and #34 from retyping six
schema names as string literals scattered through notebooks, where a typo is a
table quietly written to the wrong stream rather than an error.

`tests/test_catalog_layout.py` asserts that what is here and what Terraform
declares are the same set. A schema added to one and not the other fails
`make ci` rather than being discovered by a pipeline six weeks later.

The two streams are the reason this module is worth having at all. RFC-001 §04
holds the real harvested catalogue and the synthetic account data apart, and
says that keeping the boundary explicit in the schema is what keeps it explicit
in conversation. :func:`schema` takes the stream as a required argument, so a
caller has to say which population it is writing to before it can name a table.
"""

from collections.abc import Iterator
from dataclasses import dataclass
from typing import Final, Literal

__all__ = [
    "CATALOG",
    "LAYERS",
    "SCHEMAS",
    "STREAMS",
    "Layer",
    "Schema",
    "Stream",
    "schema",
    "schemas_for",
    "table",
]

CATALOG: Final = "chip_chat"
"""The Unity Catalog catalog. `local.uc_catalog` in the Terraform."""

Layer = Literal["bronze", "silver", "gold"]
Stream = Literal["harvested", "synthetic"]

LAYERS: Final[tuple[Layer, ...]] = ("bronze", "silver", "gold")
"""The medallion, coarsest first."""

STREAMS: Final[tuple[Stream, ...]] = ("harvested", "synthetic")
"""The two populations that must not blur.

``harvested`` is real: fetched from Chipotle's published pages, cited, versioned.
``synthetic`` is generated by ``data-gen/`` against that catalogue — personas,
orders and loyalty ledgers that never happened, composed only of items that
really exist.
"""


@dataclass(frozen=True, slots=True)
class Schema:
    """One schema in the medallion.

    Attributes:
        layer: Which medallion layer it belongs to.
        stream: Which of the two populations it holds.
    """

    layer: Layer
    stream: Stream

    @property
    def name(self) -> str:
        """The schema name, unqualified: ``bronze_harvested``."""
        return f"{self.layer}_{self.stream}"

    @property
    def full_name(self) -> str:
        """The schema name, catalog-qualified: ``chip_chat.bronze_harvested``."""
        return f"{CATALOG}.{self.name}"

    def table(self, name: str) -> str:
        """Return the fully qualified name of ``name`` in this schema."""
        return f"{self.full_name}.{name}"

    def __str__(self) -> str:
        return self.full_name


SCHEMAS: Final[tuple[Schema, ...]] = tuple(
    Schema(layer=layer, stream=stream) for layer in LAYERS for stream in STREAMS
)
"""Every schema in the medallion, layer-major.

Six, not three. Unity Catalog has no level below the schema to hang the stream
on, so the stream is a suffix — which also makes it grantable, and a table
prefix would not be. The header of ``infra/terraform/databricks_catalog.tf``
carries the full argument.
"""


def schema(layer: Layer, stream: Stream) -> Schema:
    """Return the schema for ``layer`` and ``stream``.

    Args:
        layer: ``"bronze"``, ``"silver"`` or ``"gold"``.
        stream: ``"harvested"`` for the real catalogue, ``"synthetic"`` for the
            generated account data.

    Returns:
        The matching :class:`Schema`.

    Raises:
        ValueError: If ``layer`` or ``stream`` is not one of the known values.
            The type annotations say the same thing, but a notebook parameter
            arrives as a string that nothing type-checked.
    """
    if layer not in LAYERS:
        raise ValueError(f"unknown layer {layer!r}; expected one of {LAYERS}")
    if stream not in STREAMS:
        raise ValueError(f"unknown stream {stream!r}; expected one of {STREAMS}")
    return Schema(layer=layer, stream=stream)


def table(layer: Layer, stream: Stream, name: str) -> str:
    """Return a fully qualified table name.

    Args:
        layer: The medallion layer.
        stream: The population the table describes.
        name: The unqualified table name.

    Returns:
        ``chip_chat.<layer>_<stream>.<name>``.

    Raises:
        ValueError: If ``layer`` or ``stream`` is unknown, or ``name`` is empty.
    """
    if not name:
        raise ValueError("a table needs a name")
    return schema(layer, stream).table(name)


def schemas_for(stream: Stream) -> Iterator[Schema]:
    """Yield every schema holding ``stream``, coarsest layer first."""
    for candidate in SCHEMAS:
        if candidate.stream == stream:
            yield candidate
