-- The synthetic half. Six tables, every one of them about a visitor.
--
-- The rule this file exists to make structural: EVERY VISITOR-SCOPED TABLE
-- CARRIES demo_id. Not as a convention -- demo_id is the column #43's row
-- access policies attach to, so a visitor-scoped table without one is a table
-- no policy can be written for, and the isolation guarantee has a hole in it
-- shaped exactly like that table. `09_audit.sql` turns the rule into a view
-- that names any table that breaks it, and it defaults to deny: a new table is
-- presumed visitor-scoped until it is exempted with a reason.
--
-- Two tables here have no visitor and are exempted there. `personas` is seven
-- archetypes shared by five hundred customers. `persona_fixtures` is not
-- exempted at all -- it carries demo_id, because a fixture IS a customer.
--
-- WHAT §04 LISTS AND WHAT IS HERE. RFC-001 §04 fixes this schema and issue #42
-- says to match it exactly. Six columns are here that §04's table does not
-- print, and each is here because a serving layer without it cannot do its job.
-- Every one of them is already generated by data-gen and conformed by silver,
-- so this is the shape the publish (#39) actually has to land:
--
--   order_items.demo_id            §04's own sentence -- "every visitor-scoped
--                                  table carries demo_id" -- contradicts its
--                                  own printed column list here, and #43 names
--                                  order_items in the list of tables that get a
--                                  policy. A line of an order is the visitor's;
--                                  reaching that fact through a join to orders
--                                  is not something a row access policy can do.
--   order_items.line_number        §04 keys a line by (order_id, item_id),
--                                  which cannot hold two burritos built
--                                  differently -- and a group order that cannot
--                                  is not a group order.
--   order_items.unit_price,
--   order_items.line_total         Without them orders.total is a number nobody
--                                  can audit. With them a reviewer re-derives
--                                  it from item_prices and finds it.
--   orders.channel,
--   orders.priced_restaurant_id    Two published prices per item, and thirty
--                                  restaurants publishing different ones. A
--                                  total is unexplainable until the row says
--                                  which price list, and whose.
--   loyalty_ledger.order_id,
--   loyalty_ledger.reward_name     Issue #27 requires every redemption to trace
--                                  to a published reward. A cost is not an
--                                  identity: two rewards can be priced the
--                                  same.
--
-- data-gen argued all of these first, in
-- data-gen/src/chip_chat/data_gen/records.py. This file follows it rather than
-- re-deciding, because the publish is a copy and a serving column the generator
-- does not produce is a column that arrives null forever.
--
-- persona_fixtures is §04's sixth table, added by #26, and §04 says of it that
-- "some columns above are elided". The elided ones are the measurements the
-- narrative was written from, and they are here: docs/decisions/persona-
-- fixtures.md's standard is that a reviewer who doubts the sentence re-derives
-- it from the row rather than trusting it, and a row with the sentence and none
-- of its evidence cannot be doubted usefully.
--
-- THE THREE EDITABLE COLUMNS. display_name, home_store_override and
-- stated_preferences are on demo_visitors and nowhere else, and no gold mart
-- reads demo_visitors. That containment is the whole mechanism behind PRD Q2:
-- it is not that visitors are asked not to invalidate a mart, it is that no
-- editable field is an input to one. docs/decisions/persona-editing.md, and
-- `test_schema_layout.py` asserts the placement rather than trusting this
-- paragraph.
--
-- Read 06_catalogue.sql's header for why every table is CREATE OR ALTER, why
-- the keys are declared but not enforced, and why nothing is clustered.

USE ROLE CHIP_CHAT_ADMIN;
USE SCHEMA CHIP_CHAT.ACCOUNTS;

-- --------------------------------------------------------------------------
-- personas -- seven archetypes. Not visitor-scoped: no demo_id, by design.
-- --------------------------------------------------------------------------

CREATE OR ALTER TABLE personas (
    persona_id VARCHAR NOT NULL
        COMMENT 'Stable identifier for the archetype, from data-gen''s population.toml.',
    label VARCHAR NOT NULL
        COMMENT 'What the demo calls this kind of customer out loud, e.g. The Regular.',
    home_store NUMBER(10,0)
        COMMENT 'The store this archetype''s narrative is set at. An archetype''s setting, not a customer''s: a particular customer''s store is persona_fixtures.home_store, derived from their orders, and the two may legitimately differ.',
    seed_points NUMBER(10,0)
        COMMENT 'Loyalty points the archetype starts with, before eighteen months of ledger.',
    narrative VARCHAR
        COMMENT 'One sentence describing this KIND of customer -- "same bowl, same store, the same day nearly every week". Shared by every customer of the archetype, so it names no store, no balance and no usual. The sentence a visitor is actually shown is persona_fixtures.narrative.',
    CONSTRAINT pk_personas PRIMARY KEY (persona_id)
)
COMMENT = 'The seven archetypes the synthetic population was composed from. An archetype, not a customer: five hundred customers share seven of these. Deliberately has no demo_id -- it is the one table in this schema that is about a kind of person rather than a person, which is why 09_audit.sql exempts it by name.';

-- --------------------------------------------------------------------------
-- demo_visitors -- one row per synthetic customer, and the only table a
-- visitor can write to.
-- --------------------------------------------------------------------------

CREATE OR ALTER TABLE demo_visitors (
    demo_id VARCHAR NOT NULL
        COMMENT 'The identifier every visitor-scoped row carries and every row access policy compares against. Bound to the Snowflake session by the app and absent from every tool signature -- RFC-001 §05. Spelled demo-0001.',
    display_name VARCHAR
        COMMENT 'An invented name the visitor supplied or changed. EDITABLE. There is no PII in this system by construction, and none here.',
    persona_id VARCHAR NOT NULL
        COMMENT 'Which archetype this customer is. Changed by SWITCHING, which mints a new demo_id on a clean connection, never by editing this column.',
    thread_id VARCHAR
        COMMENT 'The Foundry Agent Service thread this visitor''s conversation lives in, or null before they have said anything. The app stores the pointer here so a returning visitor resumes the same thread rather than starting again -- #9 made visitor state persistent via cookie, so this row outlives the session that created it.',
    home_store_override NUMBER(10,0)
        COMMENT 'A store the visitor has said they prefer, as a stores.store_id, or null. EDITABLE. Changes where the NEXT order would be priced, not where past orders happened -- so it may legitimately disagree with customer_360.favourite_store, and the serving layer says so out loud rather than reconciling silently.',
    stated_preferences VARCHAR
        COMMENT 'Free text the visitor has typed about what they like. EDITABLE. Applied as a filter at serving time and never as a mart input. About preference, never about allergy: an allergen answer comes from the published chart with a citation.',
    created_at TIMESTAMP_NTZ NOT NULL
        COMMENT 'When this customer''s history begins, UTC.',
    last_seen TIMESTAMP_NTZ
        COMMENT 'Their most recent activity, UTC. What the nightly reset (#47) ages a visitor out on.',
    CONSTRAINT pk_demo_visitors PRIMARY KEY (demo_id),
    CONSTRAINT fk_demo_visitors_persona FOREIGN KEY (persona_id) REFERENCES personas (persona_id)
)
COMMENT = 'The synthetic customers a public visitor is assigned one of, and the app''s own session state about them. THE THREE EDITABLE COLUMNS LIVE HERE AND NOWHERE ELSE -- display_name, home_store_override, stated_preferences -- and no gold mart reads this table. That containment is the mechanism, not a rule: there is no edit a visitor can make that a mart was computed against, so an edit cannot make one stale. Marts are computed from orders, order_items and loyalty_ledger only. docs/decisions/persona-editing.md.';

-- --------------------------------------------------------------------------
-- persona_fixtures -- the particular customers a visitor is handed.
-- --------------------------------------------------------------------------

CREATE OR ALTER TABLE persona_fixtures (
    demo_id VARCHAR NOT NULL
        COMMENT 'Which customer. Joins to demo_visitors and to every visitor-scoped table. A fixture is a real row of the population, not a template.',
    persona_id VARCHAR NOT NULL
        COMMENT 'Which archetype this customer is an exemplar of.',
    label VARCHAR NOT NULL
        COMMENT 'That archetype''s label, carried here so the entry flow renders a fixture without a second lookup.',
    rank NUMBER(10,0) NOT NULL
        COMMENT 'Position among this archetype''s fixtures, from one. Rank one is the strongest exemplar by the archetype''s own measure -- the most dominant usual for the Regular, the most varied orders for the Explorer.',
    home_store NUMBER(10,0)
        COMMENT 'Where they actually order, derived from orders.store_id. This is customer_360.favourite_store''s definition, not personas.home_store.',
    home_store_name VARCHAR
        COMMENT 'That store''s published name, or null where the locator publishes none. Read off the catalogue, never invented.',
    store_share FLOAT
        COMMENT 'The fraction of their orders placed at home_store. Near one for the Regular and not for the Explorer, which is half of what makes them different people.',
    distinct_stores NUMBER(10,0)
        COMMENT 'How many restaurants they have ordered from at all.',
    entrees_per_order FLOAT
        COMMENT 'Mean entrees per order. Above two is somebody ordering for other people.',
    order_count NUMBER(10,0)
        COMMENT 'How many orders they have placed, over the generated window.',
    lifetime_spend NUMBER(10,2)
        COMMENT 'What those orders totalled, in US dollars.',
    first_order_at TIMESTAMP_NTZ
        COMMENT 'Their first order, UTC. With last_order_at it is the span every measurement in this row was taken over.',
    last_order_at TIMESTAMP_NTZ
        COMMENT 'Their most recent order, UTC.',
    days_since_order NUMBER(10,0)
        COMMENT 'Days from last_order_at to the END OF THE GENERATED WINDOW, not to now. The window''s end is fixed, so this number is reproducible; measured against the wall clock a lapsed customer would lapse further every day.',
    points_balance NUMBER(10,0)
        COMMENT 'What their loyalty ledger sums to. Unredeemed stored value -- what the assistant surfaces unprompted to a lapsed customer.',
    usual_item_id VARCHAR
        COMMENT 'The entree of the basket they order most often, or null when they have placed no order carrying one. Null is a fact about the customer, not a gap.',
    usual_modifiers ARRAY
        COMMENT 'How they have it built: modifiers.modifier_id values of that item, sorted.',
    usual_share FLOAT
        COMMENT 'The fraction of their orders that are exactly that basket. Deliberately NOT called confidence: the usual_order mart computes a confidence its own way, nightly, and the two must not be mistaken for each other. Fixtures are chosen at the extremes of this measure so that any reasonable definition of confidence agrees about them.',
    distinct_baskets NUMBER(10,0)
        COMMENT 'How many different baskets they have ordered. The Explorer''s defining number.',
    narrative VARCHAR
        COMMENT 'The sentence a visitor is shown on being assigned this customer -- "a regular at NC Town 1 Mall, 1,288 points on the card, and 99% of 79 orders the same Chicken Bowl". Every number in it is a column of this row and every food in it is a catalogue row. Carries no name: display_name is editable, so a narrative with a name baked in goes stale the moment a visitor changes it.',
    CONSTRAINT pk_persona_fixtures PRIMARY KEY (persona_id, rank),
    CONSTRAINT fk_persona_fixtures_persona FOREIGN KEY (persona_id) REFERENCES personas (persona_id),
    CONSTRAINT fk_persona_fixtures_visitor FOREIGN KEY (demo_id) REFERENCES demo_visitors (demo_id)
)
COMMENT = 'The particular customers chosen to demonstrate each archetype, with the measurements the choice was made on. Selected only by clearing every bound its archetype sets on its own defining behaviour -- if a fixture cannot demonstrate its own metric it is not on the roster, and an archetype that cannot fill its roster contributes fewer fixtures rather than being topped up. Carries demo_id and is read BEFORE a visitor is bound, at entry, which is why it is the one table here that a row access policy would break rather than protect. docs/decisions/persona-fixtures.md.';

-- --------------------------------------------------------------------------
-- orders
-- --------------------------------------------------------------------------

CREATE OR ALTER TABLE orders (
    order_id VARCHAR NOT NULL
        COMMENT 'The identifier, spelled ord-0000001.',
    demo_id VARCHAR NOT NULL
        COMMENT 'Whose order it is. What #43''s row access policy compares against.',
    store_id NUMBER(10,0) NOT NULL
        COMMENT 'Where it happened, as a stores.store_id. Where the order WAS placed -- unaffected by a later home_store_override.',
    placed_at TIMESTAMP_NTZ NOT NULL
        COMMENT 'When, UTC, inside that restaurant''s published opening hours.',
    status VARCHAR NOT NULL
        COMMENT 'The order''s outcome. Every mart counts only settled statuses, so a cancelled order is a row that exists and is not spend.',
    total NUMBER(10,2) NOT NULL
        COMMENT 'The sum of every line, in US dollars. Re-derivable from order_items: qty times unit_price plus every modifier''s own published price.',
    channel VARCHAR NOT NULL
        COMMENT 'IN_STORE or DELIVERY -- which of the two published prices priced this order. The catalogue publishes both and they differ, so a total is unexplainable without it.',
    priced_restaurant_id NUMBER(10,0)
        COMMENT 'Whose published prices priced it. Equal to store_id where the harvest priced that restaurant, and the catalogue''s reference restaurant where it did not -- Chipotle publishes a menu per restaurant and the harvest prices as many as it was asked to.',
    CONSTRAINT pk_orders PRIMARY KEY (order_id),
    CONSTRAINT fk_orders_visitor FOREIGN KEY (demo_id) REFERENCES demo_visitors (demo_id)
)
COMMENT = 'Eighteen months of synthetic orders, one row each. Visitor-scoped: #43 attaches a row access policy on demo_id, so a session bound to one visitor cannot see another''s orders however broad the query it was handed. Read-only to visitors -- order history is the input to every mart and the evidence the assistant cites when it explains a usual order.';

-- --------------------------------------------------------------------------
-- order_items
-- --------------------------------------------------------------------------

CREATE OR ALTER TABLE order_items (
    order_id VARCHAR NOT NULL
        COMMENT 'Which order this line belongs to. Joins to orders.order_id, which carries the same demo_id.',
    line_number NUMBER(10,0) NOT NULL
        COMMENT 'Which line, from one. The key: two lines may carry the same item built differently, which is what a group order is.',
    demo_id VARCHAR NOT NULL
        COMMENT 'Whose line it is, carried here rather than reached through orders. A row access policy filters the rows of ONE table against a session variable; it cannot follow a join, so a visitor-scoped table without its own demo_id is one no policy can be written for. RFC-001 §04 omits this column from its printed list and requires it in the sentence above the list; #43 names order_items among the tables that get a policy.',
    item_id VARCHAR NOT NULL
        COMMENT 'A menu_items.item_id. Never anything else -- there is no free-text item in this system, which is what makes a fabricated SKU impossible rather than unlikely.',
    qty NUMBER(10,0) NOT NULL
        COMMENT 'How many of that item, on this line. Two of the same item built differently are two lines, not a quantity of two.',
    modifiers ARRAY
        COMMENT 'modifiers.modifier_id values, sorted. Each names both the thing modified and the thing added, so a modifier belonging to a different item cannot be attached to this one.',
    unit_price NUMBER(10,2)
        COMMENT 'The published price of one, at the order''s channel, at the restaurant that priced the order.',
    line_total NUMBER(10,2)
        COMMENT 'qty times unit_price plus every modifier''s own published price. A modifier the catalogue prices at zero is free here too, because that is what is published.',
    CONSTRAINT pk_order_items PRIMARY KEY (order_id, line_number),
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (order_id),
    CONSTRAINT fk_order_items_item FOREIGN KEY (item_id) REFERENCES CHIP_CHAT.CATALOGUE.menu_items (item_id)
)
COMMENT = 'The lines of an order: a real catalogue item, built from real modifiers. Visitor-scoped, and carries its own demo_id so that #43''s policy can be attached to it directly. The join this table exists for is order_items to menu_items -- what did they actually order -- and it is the one join a generated query is most likely to need.';

-- --------------------------------------------------------------------------
-- loyalty_ledger
-- --------------------------------------------------------------------------

CREATE OR ALTER TABLE loyalty_ledger (
    entry_id VARCHAR NOT NULL
        COMMENT 'The identifier, spelled loy-0000001.',
    demo_id VARCHAR NOT NULL
        COMMENT 'Whose points. What #43''s row access policy compares against.',
    delta NUMBER(10,0) NOT NULL
        COMMENT 'Signed points. Positive earns, negative redeems or expires. A balance is the sum of this column, never a stored number -- which is what makes the ledger the system of record for redeem-points.',
    reason VARCHAR NOT NULL
        COMMENT 'What moved the points: an earn on an order, a redemption, an expiry, or an opening balance. Every rate and every reward price behind these is read off Chipotle''s published terms rather than chosen here.',
    order_id VARCHAR
        COMMENT 'The order the movement happened on, or null for an opening balance and for an expiry -- the two movements that reference neither an order nor a reward.',
    reward_name VARCHAR
        COMMENT 'The published reward a redemption was spent on, verbatim, or null for every entry that is not a redemption. A cost is not an identity: two rewards can be priced the same, so a redemption that recorded only its cost would trace to nothing.',
    created_at TIMESTAMP_NTZ NOT NULL
        COMMENT 'When the movement happened, UTC.',
    CONSTRAINT pk_loyalty_ledger PRIMARY KEY (entry_id),
    CONSTRAINT fk_loyalty_ledger_visitor FOREIGN KEY (demo_id) REFERENCES demo_visitors (demo_id),
    CONSTRAINT fk_loyalty_ledger_order FOREIGN KEY (order_id) REFERENCES orders (order_id)
)
COMMENT = 'Every movement of loyalty points, and what moved them. Visitor-scoped. Read-only to visitors: a visitor who can mint points makes the whole action lane a toy, and this is the table redeem-points is checked against.';
